apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: sys-argocd
spec:
  destination:
    namespace: nextcloud
    # TODO: solve this with yaml merging
    server: https://kubernetes.default.svc
  source:
    repoURL: https://nextcloud.github.io/helm/ 
    chart: nextcloud
    targetRevision: 6.6.10
    helm:
      values: |
        ingress:
          enabled: true
          className: nginx
          host: nextcloud.{{ .Values.domain }}
          tls:
            - hosts:
              - nextcloud.{{ .Values.domain }}
              secretName: nextcloud-tls
          annotations:
            nginx.ingress.kubernetes.io/affinity: cookie
            nginx.ingress.kubernetes.io/enable-opentelemetry: "false"
            cert-manager.io/cluster-issuer: letsencrypt

        startupProbe:
          enabled: true

        persistence:
          enabled: true
          size: 5Gi

        nextcloud:
          configs:
            logging.config.php: |-
              <?php
              $CONFIG = array (
                'log_type' => 'file',
                'logfile' => 'nextcloud.log',
                'loglevel' => 0,
                'logdateformat' => 'F d, Y H:i:s'
                );

          host: nextcloud.{{ .Values.domain }}

          existingSecret:
            enabled: true
            secretName: nextcloud-credentials
            usernameKey: username
            passwordKey: password

          objectStore:
            s3:
              usePathStyle: true
              enabled: true
              existingSecret: nextcloud-oci
              region: eu-frankfurt-1
              secretKeys:
                accessKey: id
                secretKey: key
                bucket: bucket
                host: host
  {{- include "common" . | nindent 2 }}
