apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openldap
  namespace: ldap
spec:
  secretName: openldap-tls
  commonName: ldap.{{ .Values.clusterDomain }} 
  issuerRef:
    name: letsencrypt 
    kind: ClusterIssuer
