apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap 
  namespace: sys-argocd
spec:
  destination:
    namespace: ldap
    # TODO: solve this with yaml merging
    server: https://kubernetes.default.svc
  source:
    repoURL: https://jp-gouin.github.io/helm-openldap
    chart: openldap-stack-ha
    targetRevision: 4.3.3
    helm:
      values: |
        global:
          existingSecret: ldap-configuration
          ldapDomain: {{ .Values.domain }}

        persistence: 
          enabled: true

        phpldapadmin:
          ingress:
            enabled: true
            ingressClassName: internal
            hosts:
              - ldap.internal.{{ .Values.clusterDomain }}

        ltb-passwd:
          ingress:
            enabled: true
            ingressClassName: internal
            host: selfservice.internal.{{ .Values.clusterDomain }}
  {{- include "common" . | nindent 2 }}
