apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo-runner
  namespace: sys-argocd
spec:
  destination:
    namespace: forgejo
    # TODO: solve this with yaml merging
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/randoooom/devops
    path: charts/event 
    targetRevision: feat/nextcloud

    helm:
      values: |
        forgejo: 
          url: https://git.{{ .Values.domain }}

        existingSecret: forgejo-runner-token
  {{- include "common" . | nindent 2 }}
