{
 "title": "Wireguard",
 "description": "Metrics for Wireguard VPN",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ips",
    "label": "List of IPs",
    "query": {
     "query": "label_values(wireguard_latest_handshake_seconds,allowed_ip_0)"
    }
   },
   {
    "name": "keys",
    "label": "Public Keys",
    "query": {
     "query": "label_values(wireguard_latest_handshake_seconds{allowed_ip_0=~\"$ips\"},public_key)"
    }
   },
   {
    "name": "names",
    "label": "Names",
    "query": {
     "query": "label_values(wireguard_latest_handshake_seconds{allowed_ip_0=~\"$ips\"},friendly_name)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Connected Clients (SI)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(allowed_ip_0,friendly_name) (rate(wireguard_received_bytes_total{allowed_ip_0=~\"$ips\", public_key=~\".*$keys\", friendly_name=~\".*$names\"}[$__rate_interval])) > 0",
     "legendFormat": "{{allowed_ip_0}}: {{friendly_name}}"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate( wireguard_received_bytes_total{allowed_ip_0=~\"$ips\", public_key=~\".*$keys\", friendly_name=~\".*$names\"}[$__rate_interval]) >0",
     "legendFormat": "{{allowed_ip_0}}: {{friendly_name}}"
    }
   ]
  },
  {
   "title": "Send Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(wireguard_sent_bytes_total{allowed_ip_0=~\"$ips\", public_key=~\".*$keys\", friendly_name=~\".*$names\"}[$__rate_interval]) > 0",
     "legendFormat": "{{allowed_ip_0}}: {{friendly_name}}"
    }
   ]
  },
  {
   "title": "Latest Handshakes (Seconds)",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(wireguard_latest_handshake_seconds{allowed_ip_0=~\"$ips\", public_key=~\".*$keys\", friendly_name=~\".*$names\"}[$__rate_interval]) > 0",
     "legendFormat": "{{allowed_ip_0}}: {{friendly_name}}"
    }
   ]
  },
  {
   "title": "Latest Handshake Delay (Seconds)",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(wireguard_latest_handshake_delay_seconds{allowed_ip_0=~\"$ips\", public_key=~\".*$keys\", friendly_name=~\".*$names\"}[$__rate_interval]) > 0",
     "legendFormat": "{{allowed_ip_0}}: {{friendly_name}} {{pod}}"
    }
   ]
  }
 ]
}