---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: feedback-fusion-config
  namespace: feedback-fusion
spec:
  encryptedData:
    config.yaml: AgA4ZCXd9feSN+G2aV9C4/2LR1KxFClw6663RY1Q/XrRsACMgwUcEGM6oCzbKBF5xJCYOB1AppuS9NrZ1eQUqKbEDdC9OGaAYrjNzG+cGmOWyF6ApS30XR2oAqa0bIlCE39+V9hrAHs9kNf4lNtcdzanr/Zu7FvT1peyBjUPMJLZ+opbIIz6kVtMETeUaRhHiDrUCnb73PMs2+xjPDUwo7v83qz7OR1m3lfqZGYCDAk2Pc9UecAKJVeZrawx3fPFEaJ6jZYTLDA8qpaHM5Itfn0kXVRjo33UXujA42RCGXuWif9PpIDO+Yjgo8JvfDt2Rm1uqkZoP1yXF/hqBr+1dkGUEaSN9Dz2BMgZnBzAdyHd9APx81Mk/jIIoG+UhQe+8Y0gnvn/3pgVNw/doxm3BuEAAULj/0goo/LbHUPPPCU9O+70GGgfqQztZF+fYC7FZ2jHfSPdvsy36tSeUoT60r/vJthA+HTLvwU8U3d+oomMJ+Nj07N9ygIjq064wGVpIqMK4Z0UbTPtCdQccLupKBU8c3ESIQZ3cxKZ2uty7LX2KLAqLC9wrJoPWB3MoOeEk26ej1J2lxwXTdnVumxcfh9L8Mg75ChL7HsS//3lesLdL/2tbAS3K0oypUF+fIZfanPWzamABzhibttFVgmitCtcb1mSGN32EW5k62HlQNnH0CBFvwBVJaUBMvypuhFCytRNu3xdHrjUN1imA3fv0F/TmOrU+EPgWwElYEYxG7GI/L/G5+NS0w2m37eN07W/2qwZ/5/iyJI1Rs8MpTBMrgQhOPozADod5IDc6OWtOY7w9xYHUcdh2OCVBit7JG2WTu1x6WhGOC4deVt3JP62vBOZ83CvyvMR9ZNrhNw4BUkYP1M45Awt/gOOsSOpCeK1djknhIQfL6sW1QDW1lmtuYHFGsvAQoGWS6K+BUlu8icvOhupdbuvPiTjA4ZTfUkYXYHvIm+mC+F8rYLNvBpyIhWhj2ASfqqzn1XKpwWPxC8dHehpYH2DqfVlIy0mlrQjGG3OF6I1ZFisOLfeyntnjhUGEduc9dDgM4khjSMJ8eXxdgxZzn6INaVdyrwCLqEpMq5oV6kiEoew2uQRAvJJZXSsVBfo/UDM51WcBNmng8YQBurpJm9/aZ7a4nyNtCE4dPZK0N2Eur4NeSZqbeJ3QGt5baE2k2XnD0A/oRDnh4X26PrEOkRnZOlVg/IkVZGWOnnDyKwOzKdCLMG5aoDXrKQYw6ythOsqbQlCayMpB9fCMI3+V7nfYBLjWshR3MGYFTtmnU5UHmdiK4PvQFynLIiw5EZeQ+AKRnUTGQUfVFmLMMFadc0iEjEWfGdAPhd1Tt90wywkPM3+M62lMuu9HhbIVZibIQ1SXqvkhm7UMYxsLL8TAMbwigEe+16GfukJirRdhCcaginPC4+kztgbIIm7P3HzW+hApLAxVeqWwfV5SJdYeqDIgju18IXch5kgxgdfnlQz6+B703Ilbl5JUN7Qzv+aS5Os5UOgLHodMFHrpDrEg4dc1fCP0w==
  template:
    metadata:
      creationTimestamp: null
      name: feedback-fusion-config
      namespace: feedback-fusion
