---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: feedback-fusion-config
  namespace: feedback-fusion
spec:
  encryptedData:
    config.yaml: AgAmC13Zgf1DcT8Jjf8Ua5wfFcCvVfM4+YfgUNtB87JE7GG89UWQK5GkiM14xOWGEe78aQE44h0wV2jQqZzHo3MfcfDznSMnejxaEAlCRNINU5I35kTk3P1ri75utcf22ijvt1GavDE5D5NoeSsOkNbB4T9I0RY1W3/t24UesYK/7Bgouzd04LDXR7zaQGxlXRLGDjJiJL4GNsLVGOE36Ll0aOllz4tKvBik5nekNqelpcCHVyZc+zrUgqm559O1xeQWLFk06zdgEql6zCJWr7SshJwqcV3jrrJuja3ZUX578l0e+jBVwP0Fci/qOZVvoG0s4DXXlzGwsKeigr8fdF3tWdDzo7bnW2TNauni4SwmIaYtNhg3RXSfDiVQktCknixaOSpEhFwNOUzRMNbu+VV7HIq9NMj50b8HgFc/LBqTr4PPIbhn7end5mB8+MHbdtD3h4xSKkyzeTVLIizt/NmQAv04mLvhuVwHQOhBCee/AIJcWMMLSIcK59WZshAO1d3AwxzMpOvemrZvuZ//wBF57qf7AL2Ak4oR4DhonX2Ew3wPLsGDH6o2PYa5Ain1CAJeahtzMGvyx3foeoeH1B5AbElsf1Y198b0/vNMuQWob4RVAihakbsNc9SeNzGoi8X1+6J8FzZsrZ6wcXFBsSWeQemHxUVchMV3czKmKG7UgGqJIYMaJ4XtTf4vcYOGEgRsutH+gvmdiOABxDc+UnBApvjaExaG3vYAZJlQPYC2V/Zg6xAQqA0zjHc8O5/UlAUU/w6N89gm79WO3FpBg0MGM+v4X2g/flgcnsSJI3lGcuKp2z1s3+/q4gAkfVfRrKKCAisHxgq6oyrh5IhwHNuE8IKEXXXTrWhMvA/fbNncKX/jnpvuZ9vnDZhrcnFBeLb4AFU07kjmhWcBir3GRNgE1QCdmeroZZ/Qq0FPWXb96GzIxJf9gHXa2SLq7L81otL+r9a77Hfcjg6q6l5UvRrkk7cPw9nkmR03CXgqLNJ31kZNAxIzkf2dTobErm1+paMFRiCNR4LTGloqIucv4zRk+j+qh/rsFtqaOqH1pL5YJSa190/V03WV03T9i9ORYPX46/sflmI2uv5IEdwzHAXYo3GdZgQUBZP7/KUecSAfAspJ+NSRBEJr3OnJmnsprRNGyqysOXUwHGhgRdweYWBG7Us4KI1AthQ1FRwGIGSTSOV/DjKOPG714j5QgbuwH/crXJ7oEVMgGmeawPJLRLdYgC80orTKjAwT/2cd6kqNb7d0roJWOsLiy/hms6Oxf8xDV/0WRHt1l8BS4fQd9Wj7eXMVwGyiaxlyDqocXDRB84mxXSMBkvZUvxRvFFG4RXHyJOEI1xpJpznkb1WaT/KoeZayMd67VNECBRhdFd4pBSwZPwT7njc6LwfJeOcqIpOyYwmqVzYraBCcDQ3w39wMk8VqTA3iLxKyKaBEcuU7emr/9aHGke+KQy2h+ZMoHvjyGJP+fcrrr+cZkcm7ADp7aIugPne1Izcle1MQdPFbjVfmqwjwVwlouQ==
  template:
    metadata:
      creationTimestamp: null
      name: feedback-fusion-config
      namespace: feedback-fusion
