---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: feedback-fusion-config
  namespace: feedback-fusion
spec:
  encryptedData:
    config.yaml: AgAMq8JGlX0X6MXX5qwkPB8AHDHtDyIl3f5BD+/y/3MF8LUn/HOMnk5WXglmft8CL7QSjdFs/7zWr+YUQsK95VMUGj76wrPchi6ULdKkyZ5OqhRzzuRWJGmGeHhuistY4khtL/EL4IcvHniHtmocOhvgVs/yQSTSP2tmLI3pGdiIsXRxCIzKVuEANJsEMwe1CIfw+ypZh+Tw60eGqvJBxymL3sy2aplSLeRb2r7i60TdbEBnuME8RD28VZeukMRwI0w0qS5YEQ2IAoUOoY6oVkvwCqnC5HECmrWYOgii2VG733ina18r5m7TtXiN30jEntOgubKEMpAUDw/GLWROJvMJFz3LLwpUqXwTbGq18jrVTPGh4yae8ikpuARU7pbHg3/JhdPQLQdAgpWuia1plTv07w6d8dowiCvB0ng146Rf6dG6tPuEdb2RoEB1+YwdHRqS1yRO/e4Znh09cvAre6YvmVj3Tn2Ne/VH5jhF3Y0Dy/UM3HqIiYOfLCaB/MKL5aIY85IeaPnXqjLltD9NplurWI0RYPZlDtRwTgGJuCk4Ck8fdKqKoqg4MBvaW2LSXDNnBAZ13tBieax24DWD2e7kd5I2rMDptRgakZaQE81bvqnEkoo33op7HAcXYzdHoBFnyRp+mAYoYdBJs0TvV48fdwZUaWDzSnZ/PLOp88fb5lUOnywgySiJyrjowDMXcThNwa8HbAgfYyRvWq652i5eqGNbl9uMUdEZ88BZvegJgxCIMkXshQsCkskRujGEYwwSYrF3CHUJSAPsbadVO4LccsXE5ebhvBnfcrmkvoLP3uase+eIx/OFyHItkwcMCAVbFIoHPF5FhcLoJeEpbun8RdIc9tPwck5DRHDsEvIZK5G/IrdYRRqrscI8kVu7mrlzmxqPLKhFKGe2xD8RF9sibcN34SV0o1k2zRRwUb3TY0dHuvnbAyx3bnGkiJkDljsFeBHsUiOBfIYLo+BDm4iJo3pjQGcM7+6RL/ZI2gB9hwbo3C7CwemjVArgmc//yfBZR98OFF+UAMQygPq4iSdhxxagqPPeq6ivFMWuJRsSozZqxgqh+kbJFw7zYq1ulFeTv54i5swJ4cR7kCTOY7k2Ya65+28LO4UXNC75FZTubpjy+4Grw68FIwLb9m4Zs3D2Odr/Dexx9FVj+rOrAZcG4TqunBt9lxDuVNxyb5ftei16rP84nYUmVvXBMHUONeN+YMRtBeewQw6GHoh9HdoC3EFugiFc/AXUqr+arjt0z/uZvt4G4S9qr4YEew5dNVxssKt53uJCAXYFtFQmK8uQyIyCVhte0HTpnKUhUGyzdNv7VCDDSNB20MQJ3YNwZNxjin7M0DEBwTHdB74ih1ZGx4lFpnaolUl1aX0q2n+ciWxe1TovX16YZa6VPoXxMhT8G02OrY3QunbSi+9kvQFxqGUdiFJ0DZIWS9WKPbHWRk7iLehRlaWg4c67qpuI75DgFSMg2qrHij2tHdZBZDzSgSlLy6bbyVpqoNey+4Z3D1fytyhA/LE1NA==
  template:
    metadata:
      creationTimestamp: null
      name: feedback-fusion-config
      namespace: feedback-fusion
