---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: feedback-fusion-config
  namespace: feedback-fusion
spec:
  encryptedData:
    config.yaml: AgBqIu3Z4BRqmkQ+sEy1cRfLpqWdwyyjRA5b/SKd6YI3nETCK6Dt+aoq13GscJnQO9JADqSNwOfzVf7MJUBTXgLDDRWtYm6fxP05DAoJzeIVsDpm+kCef4SgkZnEVdnulFhId3pDyQethLAKvPzL6MQYfMWydzPQMZensLp4TgvvjxcB5mqUlx6t9HV7jYLbZr0m+EYPmqKd+YCvv17cqLOsBowLwarz4MAakwSZgnnEQx7F6TaGrd3fDpeaAWQcsD3KJKqx/DnBNal6LGdlIp0vtSoslow9XIS2S1f6PUdgKBnebaqZRAOtOBddMKb1cav+FYGBQkUDEjdWPVUy1tcm1dRzfeGXEbzBfTsALV3GKSGiv8Mp8wM8URGcR4ek6eLyTUhIhV16zxn41bAFRksDzWcpB8mYusutWyVkd/LesOdTM151C5hON6fyY41oX67xD7VkwZqbyBV3x5SdNPsPKkdYpKiToMlubCfkkBFw4Ikb32yt61GwZOs5pHoyWsVV+h7lyWatndJ+ViJJ6nNbz/CnLL82/xphT170J1bH/spolcbbaucHWVN2uQBSz1Z3NSFB2u5Bhr/doqRsm3o61qGF1hNXyCd/mH3julrGnNi1cp7fptuZnENW5Renzb61H5ituTIPBhXnJcUc/MsnDt79w+wFVzb1jtyZ33jWe8tm+BzeTfyjEFF3XIupidTP0olLBwZaVHnwT5beqftKp04EBz7sHmRxG8DL9+n/6/kRxadgmr4FqjTBY6mqfMYYUwgc7a78InfdFdVD9VQts/s8DVO8nPOH6gHWFcSzNYA7d9x/IaEMas1izmhO9opGXfEUcNCCUTzLN6VYr9/EfHkr4uXVDPlTCpN1wyFxTcO6Lcnny8+nOf0YDaubkjfI3wp37AM0j/M391Lno5awfMJQ7QbqzPEZPTct0937UzWOE4sTuuiH6yrhyXibuhlYEGgOSZVjlJJrgXrxhp5M0u9zsoG9d7LjSkKFUyyBdkHjdukvtZE6p1LP98xX0iF7abHYU3hc0l6LO0wTBwNM3JmdD4kWM/Oh41FniKs+nTag0xEqdMp3xpJwXsX8sVStvPODSuanU9B4nrW1E1nFLvr/gawLZtJm3Ujh3kgxlGN9TTHAu4Ww0Di7KXcxXDaCpmWlUTa1uluZUYC4wAocpd7docSYNJnbYQIomMD0XB82fM7fhkV8TPOtS0MTJOpqpxuTHDaVVt1csrx3EG8VCNcrzXz7yLjOOiS5bP+sV4PN40Hw9uDLInX50h+mlVgHHHVQTzKeOTLYKgWCdeffHDr8ZPitHzwT/mCBlwz9bv+i2e9ws8pltycmkKAyaXIguvYPKF5/TjKYpffUXhwXsZT1rl7kSt8ea6Op8/T/TI/LQ3GgUY/RO9/Iifqzdl2THFA3ar6nKs/uO+Adw7+wx5ddtqn+lh0QI9+F/COLEjAnoIvXqr8ePdVrKYH0pW2gjMEQgQwAb/g22IEjNT0h+FI3SpedFzA2BCmNI3kQE8tcmPfiYzFEgA==
  template:
    metadata:
      creationTimestamp: null
      name: feedback-fusion-config
      namespace: feedback-fusion
