---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: feedback-fusion-config
  namespace: feedback-fusion
spec:
  encryptedData:
    config.yaml: AgBguk42unyJiZCDsq3xQQaTjsv91Rn5gZ90PtKtjO1YBbFMLTRH9k1cxObjcicNf1oKQZ0kTgH+vgrO7g2X+hUF2uXEqS4d1AGFTrBWLODaiEkPVPsn8mBSHyjAJa6ZB+w0x0EG0RmDPnGAvlPI9nqaXwZE4DEpmsNJ4oSwe+/uROdi5AuHTO8hM8xh74TyCuZl+ilGtytzUju+CBJU5rez9Zn3oO4p25QwOuZovcC7o2P6MUc0oQMHJcoW/H7RO+tu1spd6VUcR2lbKyt1qLniSD6AcpRKRFde1IEmq5yQHt0CA7Kva9vr8/jIQa9BUQC5bSR4/Bzky8lwRc7nW1GqYPHYcNzwaOCV1qwbChZK0oFQXEgAa+4NCLkLM0kH6OgSyRnkMOaFmFHllWExTxrE60mxWjX82cPamsmB4LAGO5dizOjqPXFWgAsZswBp2oxRqtPsLOD91d5s2uoZRl34ppERUclqCugaz6QEpY5X3lxzn21p00x7AdYfy9AI9IbgwHH9ZxqiFpFIk0WecqNaOJdxXgeDUTkFGWfNlKx72Np8nIbLgenQwXMIZZDRaE3efpXJ5ZVBxvaAmdWHIzLroWHIIHyPjbdyCFhIFMXGD1znzgxvg09VD+24um1ct6/8shQMzF/t7fjVlpJWO8EWBWy2rS9EuxOswBTbsLiWdKSZa6JOa4Ix7CLpSieyMFgySK5tlZ/FKj62uv1QkRlyTGje+651mjbE/gocFoa5p1ARWK0Qp8ARJGYPWGe9kLQjh0S6OYDiUyOrjIs1ipGn+aGcD78y+Dx1mZ4urIoGkCX0if+QJoFfaRtZXKWmvD5112doDSupCglHNFR3CCvUEPsMZZZNR8H/6USgNeBlJ4+h7PC0z/+bQd8jtCXCFVwRJXdRnHxYHAq7OMbA6PRC3QsoRhKQ/aofw1ivmP0p7mHcFgRIx97cAG4pFv2e2L25YDz9m4/U1rC1xru5NREHkx3BG1bCPOkIBK+vvgkmz9b/I5+R0jKg8pIgv+nABXqY8SjvxADIXu0I5K/DbranD8H8VTmTkMSIVUx4KKpefsmvIBKbRWpSVIkk02BF2PZeUsDqqDcem3dNo6ykJ4S/OUH9jOlYXn1zEUvVJbYPzPW0E5P9+saUCXhSL6gk8vI9QKHlDFilr/pqOLhCa5DClsf+3ss5sCZAsIB9hW8Zs9kOjnn5lHAAQFt39tFelZV0hrI+iVBdef1KHI1b6et4Y3txNqtTpcGQTsvDsVgGCSkY6zZpA3Xzdw+4EvHZBTDmt0PWLjI+/22f/z748q+bOoyYk7TKkLrg5z5EvfzMo1KDPeAQ5QIYa7TLRYXPN0vTZlXRy5vnzAgX/YmL+R00LAL4LHC9D4vjFt9PvP3dfETDeeCa9NMU1v5Y9beqtG0gpJPhr8CyzOy4P6gV/hrsQI4I1DK5gOu+Kjt3zF9wOWYkDrcK2zciej2i71lEZ2u033Vrs2ukhX2kkS342EE7tvBilccBCroEs9wmK93qa0BiBMLjEm3qmw==
  template:
    metadata:
      creationTimestamp: null
      name: feedback-fusion-config
      namespace: feedback-fusion
