---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: feedback-fusion-config
  namespace: feedback-fusion
spec:
  encryptedData:
    config.yaml: AgAAjH4y82T+Q07/pItaoARMk2wnwS6YQiMsGJ4bmI87SW6Evu5MBYZJJ/pt11J9fr+nOBmL81uM4GCV8ZrL+Gky4BiTlOaqGYPnwbTwG/Z2FItNMBamq5IK8pMWfdwKI1d+DqowXPaCNSO6dHvo2N6+yFeBXcuR/aObzNp0k0YZb988/+SdBNHizr+l3HaMYVX3vGkXt2b0rO6N6zLJ90bIhQ0o4O5ddXScmXaEKXgZ22KZK1EgIbGCo3r8sD8N7uZmBBuAd2b7zCJKb6+RZTBmCNKTRJugV0T0z4YH0/VJ6GRxq1g/Jl4Kvy07k75Ep9Io2aYa30d9utDM2Dr/cc+vJtJ1uvD3ojbjrDAQ4HTAKMOckTFAyynwg97O4P3LEDwJdaDVtcFrWykYxTOdOLkvXBpg0kkFqwbdh3W81CUoJdjeUBBGCQkT7A5m/jCsVq7tLs8FMIi1i/JtdCGglgrXKqgymfvKr5A6qKsNHYsaSGIe7UVGlxH0V4j1Xwt+o77ygb+lm8YFnvl6EP5CdAmv/uPJ1MIFQu3bTyAHblYFj6g6dPtRvMtrZYAUJms1P9N1u4ZXC1ow0Kb7Sze5K1YiGClWWYCe4mu+LnbfKFbn2YCDZA7iNvcPOyF3IT6xJ7ruYlmcN4UPJULzAT4Cf2VQAt9xlloul8iu4ZSJ1Alr/F3fN8/+1bgWyq7cSopj43JQAO4TD/6kbnbcMVWSik4Au4SX2VQJQEoCq+EdVJOZ2GWkCt5ue8IVCTFhlSrK6vqNIFphT3y1fga+2N4u7HReAEL3ZY/2sE0WykeHbI92ZkNJ0wNzllxuN/5Y1QjP7bQbXqtrWAH4+DaLeY1HHwyYISZtbMeVT2JLczBhyHHKUc/T4ilfQLAxbG9BsWgXNnRgXXwOeNBW4som9ZRKFHz6RYlwGzwwePpkmBzk99/YzSGBEj+IcITgdmcnKtu4/zZWKNCFy/OOvvbeoZurqSf69hKp0EI1NOI3QFL9vb/VUCaK2hSd4tCEN8EZh6t8RmWmyNlPi6a3e4OlXF163YVPS20kZw3DJtLL6u6asyZVY44QwVKUz8AQ/3d+xWvAlcI1/oUKakvvfiZLdUN4CHA6pOoihSImK9+GMWfSetiSawSg0UCax8oj4KPyWcFhQxf6zqnWwdK2/qHLOdptwVco8WZa3YjQAGPdfla9AdVtvV+mu7U03wPG/LSElND+LUwUkE7jAdbyL4PiaDaW4dfn3J9wETukaxC+7MrXNib15hCUc4aKHlZ30qAfu1Mn8I/zW/pmjgHl/Gbr3FQKHrDOYmztiJHldv1IIgpEFtMbZT7BaAc7KS1ze56q/s9tYcSD5/4YCdFrK4jV0bjBlH8rL3uXy/KWbA4N5Mpew7JdBFpHkjLykTI9K9on3FJZBbG2hncpCQILtVqxQzyoHNvvq/NTPT5NlRPPN/9SesPlwWGZGU9EKP3aPiUTOXXhGsxZewupVDEPsEKG7ejgQ7lCQkdkG3+kJNDBt9+OnBRzOet3aNhaU8UY3Q==
  template:
    metadata:
      creationTimestamp: null
      name: feedback-fusion-config
      namespace: feedback-fusion
