---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: feedback-fusion-config
  namespace: feedback-fusion
spec:
  encryptedData:
    config.yaml: AgCmMRg8aOh5dLRgSmxi9X4m1110k93Lt0Zxtl4VdzYv0iYqlD9tKqdq384OgRYGvAe8tzdZvTjHV1N/+6RJgrDOstQULcpxkdo6aiVsIV2FFyZjuXLl31P9JaJAwicnEa/LewY62fDJQvnbFY/hEW16BnM16tvDdqKi5jXbydsfOcoFFdFcwGX0ubnw8g9W+p8IGub95X0DWMk0eRnFYfAADEM6/j4/saD8gNCBQ3RTqp3tzdajSq3f59NXaZylqMIVom2kVlbk8iUrXS0mGLVlh6AMbRG1J2GtVz3vfbrcTj3UwB4nU5JcNDuHxNRv8AALpt6LdcvaM/HMKMsp5Ld+L1CdZU987pJBO5fB857fZXYlvAa1sU8tgvbsIbfyFHrzrw59avAbAEv+jouAlpKd0yFSDr149nFhzAsNJ851Cgdn0o5SWpY1OALirYIrPAnY1n3uERWYIBcjFf44BpDUaD9m071sthhsYDU18OeuVOMgsvgffJ91d5RjUNHODMaFlCvBx6tC69dyavDkSsO+WF7jeS50uioxpztHVxybiGIR1NSrUcFG0rkWPLTMfUJIe4sYFJcR4jDslnOmtUHFs+b+kk5tmppWlmv1/KDvnJrjA/s6g5UakmMJttlXHDM2P+LAUKhBS2a2W02LDbaFIcldk4WS/PWUV1LqIvRiGViURVzpfcgoImdGenzjMDiRKUzMdQuqoTVUFfG0oaUap1Yp/ZqyG5eC8wR9hD+owPpT+C7dyiUpiOMW0fijnADfKMwqDlUEABQnyHlCYs+LMAfr/Kc/mi/xHjtflmdY94c2dHrl4ORo/TZWjl6hOwRx9ZIrk9scMt0yEFFV9xGfLV6s3Nxl+oJYGts3GsxzyFhZq1OPUksS2Cq0AUqhFpr9uEs4PYNYTIbK2gRAZFHGNL/kObTP8uScLSN9FwaleSL2OQByB1hFXhCoRtL/ZpZsp6CUBrB3b1tz+4ZJ1INArh+M1QC6tzS8m0ayMiH8y4teV/IUgcLykTtEz0Wf2wo1k07OlM7YCdTVhMp+KyrJoBgROJwhDQMWcuEgYRd4XeLko4jDEYXPBwT8bPUgBmJSpZBKcy9kuTe0k0EkrSyf/dOkNr0FDKG0P6JhwKGTrAFMlwoqtqmnPKZLWmCw0DxZQpdWW+igQW4wdvSY77gbyraYRkOhnKWhN2ZTRHoHrRLSJCk9+wzfw5JSy0RZbfVMUu4u1FrXw/Cnro7DrI+JN1kaJZ2CtKp/0WQF5l29dDcrLxhO1Ec7h3ZhNK2q5h8v3Zq0+slJ8kUWaXmdDLQy+60upJzv6XWqizAxmXK6JWjt25CnhECq5+XL3fXQglXOpB0/JP2w5xHWBRQRL5/n6469xBe28ZD95Jg1LE5owXrwlBVYal2CFqvDN9fXZ8hJTTVkoPcYTwM06swa0jXvHbfwl9V8hkhSAldmTMIRtXvgyrZbmo2Xq1p8bbJKpXJawXs9WdCDfUbJXM3JR0FUb1RZLe79VMvIWLuQBaaGnq6dGhOSZRdRoA==
  template:
    metadata:
      creationTimestamp: null
      name: feedback-fusion-config
      namespace: feedback-fusion
