---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-credentials
  namespace: nextcloud
spec:
  encryptedData:
    password: AgCalfSWtX1u6b7pZLFqhddeWXzrk4GfvINibjbqfrDWJ0KPX5HmSv803A4CIJi61RyfPCGtMa2A9IhfrXBczfsCwLB8oRZP8pWFgrJZLdrOg8O+e48B5VcsRadiY/nrKzFDb+FBw+1NQGooO4yZElADjpA3OulG0XiBTnhl2EiKkhgl5k/h+n+PElnHe0u2jXyp1dt7SsDUju76Ymwgf4omhQI7K3iUN3hjC/P4gWhmnIWo9tPO6KMPYzvdk0gnd1jSEpMcMDOzyWc26OnKJ4r1ZG3THrA9MBst7lHY+rj7tgtNkC/dcYlBbjdzvWo5KnfqjclTQUvcLyHA+aAyNuzKBjfnlVYn3hyLD9kHRsZ/c0VsrZrYLvggZPrKnacZmFsyVtB5K7R4e/NH2nx0JwH8A5RsRBA4rpKED7IKn5TqBMnp0fnEco1dcfqVbrQU0xQBUJjwI9jf4mBfKkTcn7w8D1O4PCiYMlTDtvB0qEsSiqKsMFwO5JWMEM/8+x0KVczYlPCjnlzFl1YHiJPWnFyZsLXCqEjkxI0cQrhOxtnSvrZG7pQtyw6yuGgtE491u2b+eMh6bk5CUGozUWSEaVkWLZB/cNQRgl/L+vAOHgMghMSCYpkgyxEQt/bUkKvk3Gz6fkOCrHkwgfP6CaZKqXwoLi3E6xTM57mbmKWiJW41mMnu59wooI2iK+gbAq5y2FxtbHvo74G3Om+xiSLkjpoIkTBs+efLSZyG1zfV+g5WyyqcmVkNJYs1
    username: AgAHmMiG9l5UABpcIvC+i7u8tewnUZz7GewhVo47X1asPYZ3+gZn5L47/Zf7mgWaZejlLsyVafqY7bZAj4LwDejWDeAQ+xm05feHIGSIaH0byLE0Pn9f1VJDAOQWNIAlA5VRh3wGEdXvOeztOE1QFXqvC3Dv7NHzhjR8VfxcyvN0ShxlFG71/RHb95B4eZc1cSQbpeyTopOe9A7iYRW155XMrR8z/+5pApw8BVF2PYgS8yL5LSGLVtM7SgQPlCk6UjoRGOo7fmN6ZF02NxJAWjyW/POrfSxFkK4IStfAlGY8h3A9s6KEflvllbXz4n+zB0L1OA74Co0v3cNVVaI3xGZ6sXz5hsDScnlAKdA4W0qfdjJagfsNjnfbm15SG/5jQhMK8KhGrbMgfL7gh15yixBh4gflW6hOec699Oh6COoXy3C7lIQjhX6fD9gh9589AGjZm4YiWyV8ATr3LiidZpgMR17NXPHeIJWM5rm+Z3Jh3RKDYdlQ45COppzIqeA1IA+Wf3+sfYDMg5suXshmtt/Fcm6B7r2R0Cs+Q0wmc270se9etBErRuKqvas7tPjB301B/BnzKpFSHu89EnV5BItRl/whXie9sXxM3FoLMTI8dBUrEPQNc01Udk9n3qJ21u/FFg8Ux4Jv3MmShHdG3xNMHcRtZSqDlmH6dItC2oUMxwJLQk5uYc5LtQksIK2Cvm88G3fi6A==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-credentials
      namespace: nextcloud
