apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feedback-fusion-postgres 
  namespace: sys-argocd
spec:
  destination:
    namespace: feedback-fusion
    # TODO: solve this with yaml merging
    server: https://kubernetes.default.svc
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: postgresql
    targetRevision: 16.2.5
    helm:
      values: |
        global:
          postgresql:
            auth:
              username: feedback-fusion
              database: feedback-fusion
              existingSecret: postgres-credentials
  {{- include "common" . | nindent 2 }}
