apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event
  namespace: sys-argocd
spec:
  destination:
    namespace: event
    # TODO: solve this with yaml merging
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/randoooom/devops
    path: charts/event 
    targetRevision: main 

    helm:
      values: |
        domain: event.{{ .Values.domain }}
        clusterDomain: {{ .Values.clusterDomain }}

        ingress:
          annotations:
            nginx.ingress.kubernetes.io/enable-opentelemetry: "false"
          hosts:
            - host: event.{{ .Values.domain }}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - event.{{ .Values.domain }}
              secretName: event-tls
        surrealdb:
          ingress:
            annotations:
              nginx.ingress.kubernetes.io/enable-opentelemetry: "false"
            hosts:
              - host: surrealdb.{{ .Values.clusterDomain }}
                paths:
                  - path: /
                    pathType: Prefix
  {{- include "common" (dict "linkerd" "enabled" "Values" .Values) | nindent 2 }}
