apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel-postgres 
  namespace: sys-argocd
spec:
  destination:
    namespace: zitadel
    # TODO: solve this with yaml merging
    server: https://kubernetes.default.svc
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: postgresql
    targetRevision: 16.2.5
    helm:
      values: |
        global:
          postgresql:
            auth:
              username: zitadel
              database: zitadel
              existingSecret: postgres-credentials

        primary:
          persistence:
            size: 4Gi
  {{- include "common" . | nindent 2 }}
