apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event
  namespace: sys-argocd
spec:
  destination:
    namespace: event
    # TODO: solve this with yaml merging
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/randoooom/devops
      path: charts/event 
      targetRevision: main 

      helm:
        values: |
          domain: event.randoms.rocks
          clusterDomain: pu.randoms.rocks

          ingress:
            enabled: false 
          surrealdb:
            ingress:
              enabled: false 
    - repoURL: https://github.com/randoooom/devops.git
      path: gitops/event/manifests
      targetRevision: main
  project: randoms-rocks 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
