# Default values for event.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

domain: event.example.com

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/randoooom/eventplanner
  # This sets the pull policy for images.
  pullPolicy: Always 
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

#This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: nginx
  hosts: []
  tls: []

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

surrealdb:
  ingress:
    className: nginx
    enabled: true

  podExtraEnv:
    - name: SURREAL_PASS
      valueFrom:
        secretKeyRef:
          name: surrealdb-credentials
          key: password
    - name: SURREAL_USER
      valueFrom:
        secretKeyRef:
          name: surrealdb-credentials
          key: username
