---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: surrealdb-credentials
  namespace: event
spec:
  encryptedData:
    password: AgAo2Hzcq7Wg7BjzQR3fCa++poseBp+QuhO85k2Q4F/WZY0GFcwA9sLVb9bUf/Dd0Nn1DnhucXU2piFwhLtjlSuB7VBJeEf/cB4mQm23Obk3uJxyPyvobInMyVyzINL/+UWEne1HeP873kkagx0gxXi6ILS/5NYTWuVgotEHF5SdkOtIc9bZoElY/JX68Z4mJjZr7fo7V5KrCOR9rzdqVXK4FYMacUa8+4qcsp6pd8dD4A55KQVc/BfrenSRRbIxZDViCrp3X1h4wnaZ7A+a3lh2mRgVczW36Bbd6pwACGr47M+wbVeF5E8X8UcABG2wAA4OX35ZJOkOsSXthy+x10IMB50SfY/yQhPamyB6Yu5xm6y3mUG16t61DYihXPdc158bhVYxTcIVw2n74qmz7qh1ysCnsR0jEgscbGTqqO8AIO5kvmNikwhHLzuoffuq7VI5WlgfjHcbsJjCuxX4o/PpmakjX3I7y0OmoL41bekiix2STrcCm/1/kt1oRE2WmCQtmoOXdm0iEwcBqSJNVD29D30RsBRx9ZB58KoJKTeTNvEtEY3ZoMEHUV3At3U5oTPFsxuMLQ5MxqODokOv7KAfmSx4kvfW5T/A2WH1K5ErR2fX+CEHWJ+zSrz/kccLbAnDE5MuUzpk3NPblicH0lWkBj+rOAAz50FSbYBouGURB+1IRLpnvJtzK5i6batugEP181U4jSrDkryEF3tMUmPuG/fdlmMEsWvdO0n1EcpAAtAmHsJr2jfZMoQxuAItqkUjlr+HjdtggijOqtPLjBn5LbEJZOZKNd2YWRp8emPNzA==
    username: AgCj1L7sffFDympzQb1Am410R4kCq5xL6YP1e3bxfTL15AUB177y4JiIzmwKgsZ9zo2f18TUMoG2F8lvyqoo+eS54+BKROcW7oEEKsNO+dIoiAwt8oQvaGHtQn9kdOCmXt7jwdvY9uLumhJ4idYa57q+746/M3rJH0b4slht6Ge4VFkCAk275QRuM6MJXtD5nocv8qUcR8/VdQXVQgB/CT53ao79x3Dg6QsUXTattXNd3W79eGtM/6KWynu7UD1Im/voAMs4KmrD3OqdzMajxJyu7LCgniJ7Sr8j+xRFtCJ8ja9p+m60SAA01qnZpVgdpEYLxugpgTlvnQpoRW+1djKmuAiHsuYDUygTH1qyfnKlmXijmi7DGVcMrd/f8s7l8or6Kce+F6SCc34QZeVaO5n73NemUkt4z+sG2D/6YcIeM+9RkHaOmz7Z4JiMm+zRDlkvVufXNneYuTgL6PjyRXEwsNcqzUfG1PxT0nDoSOzxhA4Xa4wKikbHDIsBkC614U0dAyaYcsMBLeiHaq7LEuhf5KCjYus/LshbN2ksDMwcmPXqd7/Flqom4Fo3c6puMvopQHb4vhVjaec9zKfr3F+nqbRLwMeAhon5sUV8mKL6QhQZ/+yJC53ctnX+0grwWPBl7DBidawgPWedqjxHViHKx9AHKyNwilJv9zFjCmenZVqzN0BAam3HJJMwgikqYAmSFfNh1ZgAiI8FLg==
  template:
    metadata:
      creationTimestamp: null
      name: surrealdb-credentials
      namespace: event
