---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: surrealdb-credentials
  namespace: event
spec:
  encryptedData:
    password: AgApOADXsgUjzz4+NFe5tEYn8o07lJDi3ALM4aiVd0dDCwCMgXBbnjjP1KgulGfROfCcXMbIbDWkrefkKuM27RdQuE8Q4vv3x0hZvuoZAhVX/pA6MU2pEBUyLLH4oBcl59egmKbKciojAkRSaiMywes3bsH3/Ssy1K+MIZ6nkdoiz+WaGi7+Z09AqosyBSa69QKRsrNf8u2ADrWx+mbZ0aVq9KK/gJIq3jyWpvqxLXWik3a/GWfYjCNG56M7ips12v26TgyJlC+njtbQckCQzcOUgco6tm6jncQk/2DXe6+4IpyxyTR/Ju9ggdoYwFHhZNQd6LhNV7iayFkhpOBjd3MT0eDUsOe7iH9LbbH4S7bGo66QrzYB8IlhJJ4hMVclUpRQ51jETYVVOwWT+/m4tHN8dNQ9dPua58/MV/D4yX86ibXkXPdKYjfL6GTbV58KfcNrVO2+MSg4Kv5pivjiEVd9HnPOUWubhYW9qDXmtvAp2fiYJbL3AQACphOm5v3XIoZYAzfFOmohNQsmGPHtvg9U/vyX9K0Hpa0XxRv3c9qCmpVEidQh5sGDnUToVKLkrahTFZI2t9nuUhYSpkv3SFGXweda85yHePVKBD2aryibCEBocvQ4nfx754G/xiuXZgdtwSj/Uy8/Fh7BO7UUp9Ev3j/79REffOc6HhWoFZy6I77gNfCfPU/FjSlNXm1o/NmU2pg6WBNu+6uxwmiaTVIz6A/3bm7U8VeffnMFZfDSFjyCoEYtuCfOgAIAeTyhaZxsNY9EEtAyD+3Rblp4cNOaF91mMs5SXOVCbs3OZMwNNA==
    username: AgBQzcypwOhpfGk+ph18ny8OLRy0fw9P5SYi91TDpdizLYI6KE1wtdR/ZgGPNuk0LeQenpwa8M6w7YBiysCdQKMyMt33iNiVhNZlnjn1H1jopBd3XMX9W7TbPjs942XqJH8o3VxTN2a6JEHA7h7Wkq2pab77ca3sCmZ7hItIp7VBePS+NuNaGIzYHUKAXsaJh4wUasXoH++jPCFYWzduWIY6Omf/23pr9KwNxyHKA7nmaARZKfAIVzWn/1wv6PmsHGq9lomKX4tAGskEu9jK6bc4LRP2lunk/ZRTA7Yv8YK3ig4ACxCnWQ+vo6jev66ZuCU5ZnuR4YvAFmWtEnVrHlxnNrgq4GDJgUY/ktG7pMD3OOkEuYggrhXSKbSAFJaRLSlna3iXCUu688RSUl+5cMzxx42CW0bkCZG5C0OQ6KbFhdPINUzFHso+oJsx8TG1VahMIoC+4QRy5KapoJGNnBVEEGOCFxoJsz7MIj5kb1EyiiuI3j0HNhbfuNOg/o4yHaca9ZeoBMK8gv2DGbLc5l+I7flghmVoS4T1Q7uVNVJ6one2s5sereQcAYw0DQJG7GHq0mgflcHtNnAc0rD+ioE0OxeeQWNpDhOofN06Y5eB6pInh+NA3kxYj4DEKmxPE62YrVBZgG/PuNxwuBwjlaXgT0JZMwLsdtz2WQDN1pQdBAUtrylxN04IWEhSea0OOqboAhbfLSyH0p2ZgQ==
  template:
    metadata:
      creationTimestamp: null
      name: surrealdb-credentials
      namespace: event
