---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: surrealdb-credentials
  namespace: event
spec:
  encryptedData:
    password: AgA1xtDUA3p85AehpMNnUZn6tJyvCnt9KZcyNe3ScyDFeKJxm/XzvaBm4rsnalrN/TqZQ3w7upK6bRos9rpIT4Oh1MyiJAaII3SOl/BZNoWO8PXC4kGhTAchNeE3hoEKqPny1LxF8Hy6yGra4kTWtVWf83h1IfFDOz/mqYDIst0h/Uivufnhb/rEusveS6gErBrwa+t2dm1Hpagh95iWrCFkf/tydn+5OPoxf+nUt5JGmFeMWOOeZ+DmLcRI/ykeW4oY3OhpoR9ELJCXq3fjINOu9xIfVEW+BygZXxB5NzYCLyDCvy/eL4qd6yACiC44ta8KS4p1ujT/WqCNwjl2kgeSRvSw2suUpRrWruPV8Av7jmPK6gSrCRzMhd73VTkIb0GqUvuki9qEYUbbjnN/WnKG+7EwaPMZJj6MnpT+TqHzCY4oNwlHNUHlJtK1H/wNs567eUPV1mbV9Q0q9uaMqMkCeCWfvpkTLamjiILGicD8rtQrQ6QFtRCTIFZBmUxrvx12pJDoDzWiOtYTnSP8IOnR/kg4noXP6ABRIwFVOIXbQUf9PunOxUcEo7XZFPIKmnO3t7R8aUOGYE5yUVJR4GffBwTc5oIUk1oFXeNdOo1NMraZWZGvoxE/9Yb+J/LrJRY+dEM4Bq57bcqnyNU9Mxb7bZJadQqTPs8ACQsW85bklewv0BfCGKBVDLG5jWD1bg2wvlPcvathplxty4Mg899pGit9UzQWWW4fOM84JfFVcjFQx8Zu3wyel4tKHoKn0T/OPDdKVGhhpWeWeUI7vHuQTQQmzCOPCkvwO3RzlbK8qA==
    username: AgBoLkpvVEZQVlCoziYzCCs6CS44yLUM/3/UHXbvBkEF08QW+DjXBSsk993c7vn1rrBsRR3sPMD0V/iWV4MOd86Es9wJATk+yIyO5xs/HoZoNX83MOgiybdn1KUDJB52kMwE1thFBttjY/SpMetvt4lbXQjlzVOwCEKbzmY5R4SvIniTCL6N3fDZV1hC3ZZffG9e+jMG2P9GEkIJJmsnt4F1x0cJn7SyCBe+C8ddvhXg7gWrSrm+Ho7sH3j98DnNHrLmIgE3fN1fBkThqdi58rcpKARbMKS0XBD+5powycTEfXwSV/3uRHQD4FZtQdsOGrVLjjWcjUk7wZywjbUAquwi5fphCcxFkwRrCz8jnMJ+5cC3Uy0Yqrrsf7+xaV6YQO5A4PN+sZAjkdqq0KuQPBXBjUBUlqoGC7UcqSx7JVtOZRjV5cPEeMB2GXDGxjvTQbaJ34Um3ScivXNMR769MopIRo/E6vUqu/uQbpbmmUAw6CpFyjOvGRLJvbBO2fLZneuSSoaL2vcjEi2+brZyepazO1FN4jsNGfkbXNBbCdSp+kFme4Ok+H1e0LX8pseqLYjThEweUiay+YfxIUnzX42CWhgDpkBefzy2u53i8wheZ9mdu6yJMT8Z+I4msk7hmdiQDvxmzRcxWMd6LnrzTz5S8MxTg2rknZunaOQ2LsSLvZia4V5oRplDAZ1pXicAUB7fUD5UF3ZpG2M8XA==
  template:
    metadata:
      creationTimestamp: null
      name: surrealdb-credentials
      namespace: event
