---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: surrealdb-credentials
  namespace: event
spec:
  encryptedData:
    password: AgBbBopL6PENx6uuXmeyFXyPO1tmRXjdEokb/avdffRu3savNfUvGDx5fNEFUF2u8oMQVWsUxu1fCV3FYLFNMjb6mI5NOkKqUYZJUTGkJD/xpo54Y6e7FOVXDTyqtkqsG7jMntdGKyXFrwIzHFlF1fNhTdBhL7NJ3aS8p/+V5DHLLWsAnNIzJwB0d3wa+xbfDaFD271JFLCENVmxZuGUfrQTN0pJecHZ71TZRjGYVEhKsAtbnl5KmpO4o2RwqnV32UCIrwjORDNH0RFfRPXk7kiS9xm1RSjpbSDTmsB7Zb9UlR7LkHXFeVVv2QRRYTCfIGq3OkP+w7JvnUZ4Zk+oybxaBi07eDU8JjEFNaKvvRfL3n73PcOyrVstAIbZuFdt7BqYS3OauPC7zSLXBD1yCZxmWq+IrNzKb9FrTIVqKJ0+vRlfMX+znEPAUwloB/8WSt2QhhPdtF5XvKpQRZ9vsv6uqXeEjtE7k6t/7YFA5QLy551m91i0ubJIDmY98KvDH7gHeI48gf4FZ0zSyfyWyCClc7rwA0DtUguq5LI4ol+dY2ajc9STDwRaibe+xoVTL798gP7GiyrsXC7svc0fpFWVj+evZlFfQVA2NngYMMNXhASJp/OhS76RPwtszv7ESvLrS5O0NOml08D9TSZZPfEul9z+srSfFHgmtJjrLBjLYj2I78YEjS635nDypdsnfP9lhpr9NCSxt4WqSMgPL8I2OfFXFwlmgLZOnKEa+2hJBBev+OBhfiN25OHKVHQQSLDG4HwfvKAH+vbOSFKu8OduROorDB2jz4zHcp0rvF4CZw==
    username: AgBdJUdzb4YZf0sGoFpXswRvECeIwTaIopL2pLVPrYNqxRwavjtkj8+10Cl+2uov8pYZJ8TuSQgLJRPiyo943uT/3Nnp6bEfdnjy1tiGXxe0C5kJKC4E5b7a03jv1z3S8/Vpj1wsA98QsBCkMdHPdvoH7xbjpzZ6+qvU2LQrtpkmNZSH4SMEMI2p8skuEjvzvl7f9xXlCAOWRsrsZrvETS8tmKi+rq0p/atUXyKLFiqAmSz25dlVVQrJ6S96c6/HneGeZclSUEtfU+v8PVx5x8Trjk2LjZnzTXvRm/BRiiQaDi/Dw6NITSBeuVb9h5kLP/nGBj+nnK8XpqbePUwblU3cRGBFL+7f/+WSvm7dxQAAP/VcrdsrfGJeOrGXUq7OzX5YPcIUN17CRbkxcdu7AaM8xu8qDXGD6l5/Gj1s8C0/1eG430Tu6JzbrATk7Uekqx6ovWaDgk8PmGfFJpEmEIMF982J7r1mh9l0xIVHj8tKII4ZjHlIdJ6tgPdxlE2e/Zvm2xsbcNhHmlTziQUD0C4Eq6gGnn2fosT6P/J6KOl2HLiD0/966cxUUEOa9Zh5ORZkZbR+xOrpCAmWjOzYxiobkM7rGZs07qCn+Lypd4OcInac5UVyWc9DkWWihndf/D9hDwJxUONLuTnj3eRgUaxUVlIHXCWpINpzgE731vFBncyukqtCotiSWrfJsUZskez6FyWuHtgn1wJCEw==
  template:
    metadata:
      creationTimestamp: null
      name: surrealdb-credentials
      namespace: event
