---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: surrealdb-credentials
  namespace: event
spec:
  encryptedData:
    password: AgBOWedNq4Kt0qvwj+IIPmkyLMowlpwOrlQ7PMS4s79BEJlvNGfJdbZIejVNaL4J1D5w2gd1hNcYcel4TDkF8A2CibixzorZOdqRtJMoDTQGjxLI8ayz0J606sE/fL/z+gGEZmqRXSMACHAkB9SyCQl03kilzRK5yTTafaHWL7JKvm0Tz/mKovJHwAdoHla+B58mC2MYq3q+e6B+q9mZwfIgcGRkaFAlyhv17mhy2xNN8N8r/dBko86E5z33kB17la2ZRMdNOSXG1jmUdQ6m1l98Zn4IWgfoYyfDIPCKGZa1L6UEDPWvF8j/50Ce6YEVWrU2EpI9U89gGbBovKog/NxUAwLITN0CpdgW9Zq30Nm6haMrmhjtTpesyLTwLWtkAP0EaoxrSoCHg1kIbsUTW/N7Zvj+Dv7xepm6HNXCelfgu/uBN+90Gk0+JmxJeAk7DpCk7C7GdSgdqnQ3e6HFOTSeqSBoqQ/3/4DdW9nR+XH1cw+qgUmN/KxXDT6SnJtcVzncr8ImXfEhFS6D+nEdI4LjuGAaY+k6j6UyM9qAWh8OaUNS/hjQm6zt/p16f5Gc/R8HG+U6mTiE9bMKjFRnaZy7jtvI/ZpH/ot4aapo+UWc5PEYzSZQxM+D9kEWupWwUtMOqOxiqyZWITZ3CyliFdji8hKjz/hZBAYtofQSRbDxLxLGGPWzwWGl4UIoF7+Hk2KRtVLVypnUpk1sPrpwaYZT8OjRnTzhRP9lVwbRcDfgTFNrQu6WyW1W8N4qi1TFrB0+frwwPub34r3asdd6Rr/y9sE2a7K4YpceyOXwPyK8kg==
    username: AgCc7VnOMpxOy+hCpJsadOaiU9o/sKhvJ5O/L/WGNzWqkBt4jNtZFBSQwBjTfFS0fYLNXhLSVelGAzJ5ZPGyLJwG94KU3k6uZE8pdU3Jq4+V7HFXNN7lsxF60AfpY+NfgWGZAJuO9x5Pmo63k2wONF94XFsEZLMcONbRbykGHGboG0CsceYTNjZ0F98yJ81V4hiDC7ZxhFE1ggrMWeky2id5qISa0LLSuBCGaWIKJaRMtN7CHX/+nG7Q8pi5UzmSCuurut8r58hTniXF5Hen1L1bbWso5W2WalecPmaRAIHc6WtuTG5vn5oCOiWyzGOHIN8jZLQUehhamTH2tTPK8ZbZc78LE+Enhw5qrb904X9rbXKNd330mRLghEH3bgGit45hfQXHvxz7zfL5KvlEd72mT+49KzMl+Zhhx5mTA0FOISO7UptUUTZJ01gmFfukF+WzuaVNATdiywChoPUIn2Q3NmDxQnJH/BRdU0BX8O0DclD9CGe9ilfh593bkunzqpsaLpF7zIBRMBY0zWZbfiBfyWgkKLYZGoInSScDHgFh9Nv+jGxmHwMgByB7zQakeXFeitBsDvXebV6ZxcWegmMlvMKYto4qUQXyt6OsJdfu7YKN/2sNPmTn+QjmEti+VjivgnrxJRmgoyJRRbx19BBWVmp4Bd+fq9CNIQqFIm9dezvBjyrQfK7l4MDBim+jBBC4BXETz5r7vMhHnQ==
  template:
    metadata:
      creationTimestamp: null
      name: surrealdb-credentials
      namespace: event
