---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: surrealdb-credentials
  namespace: event
spec:
  encryptedData:
    password: AgBUyo+2jRiw1eSJxpDQmwJc6kzXkW1fXWy7k/HNTUmEVP0pwKjol6FCgO+CrGjiVp5yHop7Ij6MWcUpAaoDwY4J7RGLo1R35w1DsS9XOMn+cJhYk/PJCf/OhbusIUe2+/4Xais2gGejutjW0Ol0I6qPxIvtCMxE1HdIJ67QMCIsddhSPGjbwxNBDiEYbZgZuAeKx8tYoo+zDwBrX2OqHB5q0KdmbD3IKPEdMFO/MhBcHLrKpNE1eVCYsXvFvpe8BNwI1JcQdOefMWr0mSoqKl+dy/EJ1z28xLtHdfiGUf2ucTIwH8zcJ5fcPRvuLpWsayFzG7Fk7eKRIULrB1s+wwOmO7Zpprn5hlNcdKSZuIh4DMIcbubyH8OxlDmrEmwsMDQphioA7D3Iim/RmM+KGfATHNSMu6HgMraTFGD28jTqY4peHOs5tfX9UQNAdVKE9ABcfA7BeJaeBwEV/AWCPUjb3HXHqkiMeodkUZ2BIFCRs/7EFIGupiaF5+JN9at7oZzEUsPZeKjz/MKufZz87+sCj2JbcMm5FY0drNsW+4+tuctNKsTeR++FIyjjLXcgDEhBzBgolzRayu2ulYQvyrRySC7RSxNFOw0qafiT6daRuzInOAW4GQTHfAJjRIJmB/hIONU4rQIEHw6OBjhVn/RNtRyrMya982+Ys1ylnCeQLMV1vR/Mxr2AIUe9oVnlC+lqDE5u71OBc2pRGkpEsrn4qA2qqR4d3KkZ3iEY3oTtZ9t6sX8FrWJx+bQSeIQWNMN5WFTzP8eze7OVs1cK3PmJ3frQfDiAN5vAimIyoLSfXw==
    username: AgAL70lvf+4Wmpv0eahOScq/LpcWTVcbVBVI9h+DPx73CR0m60C/R4PY2SxWZ4D01cF6iJw/p+hzt6D8hJvAByhHewoH6iDMP4vkyrrmtGou95SLrPp9pcXyXMVTLVFE/+UJSmhvabgIkdlLdpyAmO5+fJlTo3k3cdD8OM2OXODAwcwov0gmagtfXo9lp+nIDyK2NFNuYqe1NpCRZiMKzsNnTLGCVqJhjahWPc/rJbykGHcauMQN0cawuGnX++8K+g/DGtLfQRvcZ8OakECUgH4hgKf9TpTm5Vnr353+RrHBT5XT/I/ghqbzwPFWYkEoYfgzgDavQTBTlmg5rYcQA6nT1HpOX4fyIHSTFKxudQcO3STfQUFrmYkYyKp2Uuh+Yned/iZylWD/hmQjkKE0G13pm0asFBiVkJal4k3pPHtM9UUO+QpPToWH1My88jfREMehKtwK1YZ02oDKc1sf7EYsR7uuapHCz2byBK8fqbHJxsEsCdTjpnxf0b29k9dNMuSL86rUh9wUWfwU5DIg/Pba0k/qNDLonqQLB9TglUbH7FH6Ub4nnpNcZOLl15rT/TTaYtLIAnu++Xmh2L9GCyInJ3FVRRGQBEe+zGOFQGTmrolswSARc4DYcU0gnVk1C2htAveWOF0iI3k7+uZyvkbhID0XnYfQrYRS3P816CdP4M04QkD/rfSeSfjglWOO3zXvvvPuAKNOvlXi7Q==
  template:
    metadata:
      creationTimestamp: null
      name: surrealdb-credentials
      namespace: event
