---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: surrealdb-credentials
  namespace: event
spec:
  encryptedData:
    password: AgAk4kOhwLoP9B5+4utyNlBdGKJCxBKMzufM4HWVYVKLaLFkvZ+TT2u3Z+BGuKyffcuD+XR6XbBC3NwdRleheq6tPiL4KWX7FTvEc7n45CiehD2I7YdUr//tTcXXshNv6pu88qc8BkNg6h3hPx2mGpP9BD8y4WyRg8FzkqYcleZtjz14AvrRAypHYIedknE3Dwsog7sUe6ILFlMkx3jy8bdfGNdMvvJw2FE3/0leHPMAP9oKDaHd5NAfEF6j7Gl1SMtJIcOeAzeM+D59a32O/Fpo7qH/kiLtS2UlBkJMVyw9hlIL25M3LWEy1wIwG2kSuF+SsmOIqrA6MeChOFGTA14grKT0oGsK+BGltmbbS9PDc6KkTWxlvaYJOs010UeSoIsaam+6TOgsDReHyFF8jetoXGmV9A/f/DIoS3NA1yhzKqD89YpVfM3qy+pIMvDBED31ohl1w64wkdrqNa9FKVqvcsfPt751sXviqYRIxAybaAFaz5K1cyaDFPhfBvAkzuaOmIb5m8fCRYRnAd+JhxjiDUPoWK+xf30a/QpqrXU+MP6N4o4sAA6O3CK30OyJ2is09/tXTT0ZvvwcdkNgFzHYkIUjpuyo5Z7bG4ad6N+jqhce6C7eseyfQaniEOMIS1esyzKoPWjv216PBtBhrQBSQFh9HkU+6sq8sJFL3ORLhJHDpbppCm9FCbohVWKZprDwLoP5AJeFx8RMCz7EI1k9yNr3tMsnQqTKYqg/1OWz8mehawqPTI23cO07ki4B2GAGYhuEBPRumsdnHVQJ6DjBQJq2w9GqW8cQm22cTKn+fA==
    username: AgAJ1ZFYHey/VDZ72tVM4nBPF1g/2K2iyJq88uG9a0fimy4MdUgtRJVHJTSJtdAz6JoA71OrZgfo9UrL4z3ySviO3czNNzQQYRYjiJmhjR7kApwX8B79g6vXOPUo5zMOGgtepFysLzMZs5ULuw9ptFYaTyQbF6ggCQdian0kxPMKg0x5VW1yXb8M7ROXOmwLsnfZE0+Nd6ZYEBs28WuzLp7gXDgHyUzTj2ZF83GK1I8qfzLlrikyneJRKsMVK8chBFXXg2YH9GVd4qP8EIMGy8Z3baNKCo+1NS0pT75uDbqmfyVcR1fqgX4Es0AnYz0XicUh48B17wf+f05U8mS1o7U3MIolRjYSvln4KiS8yMcrPdw1jRiFjdso+JUv3MytGtuIHhOoBP/xEkReduUfnoX7XIb17p4IUl8Yt4iQW0z52LBYc3g5bQ66hYRMFodKaJtjmgPjfSwt+2GOw0Y5HijWxHN5GECFCJ7ebfb30aHpQIkVN+C+j5DDEiPA7Iil1wF2m7mehbHb5LNL3ICfi4OU7MTGC8cxmdgCkszTzbrtJKwXjF7m1bWzeTw0WWoJEPobcxzX1ziu92nKD0vIaV/MJhP1+jFEiQt9VJuq1Ocy0wfkCXLoRWU7uU/Ll1Kg4iMw/UHja1znFao17YE/0y2nfCAg4Z4NUnKAQtG0W4PGqs9AgVBNn29j7Q/Q75TM3butONkTyNm/JSyyAQ==
  template:
    metadata:
      creationTimestamp: null
      name: surrealdb-credentials
      namespace: event
