---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgCorl0KY+W7lDkHrWWANnlUPLhIg6XJeGKOHNisQblS1wCBFVgNdW8H22QO/R8as1tncs4r1p1IfHbpf8iw9uv+wvRCjCnswAKZWON7cUJRticwpMh9QpleOp3G4zLjH8yaBm7/cUmGviIAEE7PGA+z61QQPTLPoa5rhIJb9j1s+/bqlNrbP0XfrjrtTOYiD8Kl+/klytVH/517XlxQuOsmVl1Q8eRZ9y4trNt5t2O3kCohSKpQLV/zBvqx/ZY+8B2bsR0XJzMTy8uoTkynMcwmHHO/mGA8LHh/oW+vhrfoQIUwp5bE0NJkr0c/G2Xnk46ED3wi+1d0OlSWmwQnXkgrbXpBYPe8ZQE72vpVynCkC1Z3OlW3z8kwOkao+XMNKo5iaEX8o43+6V17FPJejtuiyFyihBCIr0e7Kv94hBtLgAp4V+6IH56AycOezE4Vw/V55Gcm6kGdu1ykJ8LW1simMCUk7/0Rr0ia4Xe+1QyzH8VS63fXa4WmT9TwwoIa8BSpghxGh8mhuscTr0+1VTudgEwHgE/nI8zcNGfoSiE8VUl1tLC+FocItTM6CDiTTgORm5Rm9HGkBeHvjMmpPH8Zzbv/pJOCwH/wHObgHPdFn0VwIAkqo1K7F/13aM2QJxPG88cAS6xKpyfc/gkuvTcby+dYEuXVNrNX01+LQs9bzwMM4F7MCi9uSXuI+Pz+A8Wq99RAGJ1lExoW05eYUFreos35UXqv+bdhe2bD1WA9UZwu75RO2jRn
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
