---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgAlc5yUvKIX8mbYOR+b7dJyZ54i7N+YMbZyfqjBeuHwprJrpHqbTIQ1va/yjJ0bfPWcyzcBHHp6Yj7z734w6fkOet0EPs8C8tYDyyuETTmw4Fp/oiXJNqabwg3M7C6kxDSakyr65kO5NOQgzje6XxvnOPE8cA0KQwRXeAOs6R0V6p3Nw3weFsgI0QYiegJi+YYVG8NggztZ5td+C0qGga+BIt0dvKpTCbLQ3MP1snBYkCvAqTLZwsHIEYqaVsCU+xm8FCpkrf1XgAxeTU4QvybYoop7OP+JPmAyqx4oQMFxZB5pi07x8XHasBHpQz1kTMzzPhzCj1fKlSdQT3p35vRrPcqoJDbhpF4x6AIAZvUyAr8ZGvJOCxeb1zVdOgXVf0xrenDcyqyT98c27XD6gtpZ4684ofIYBuDmS8pnoicrXsZingVIwwo+/BqfGFPuLktpX9zESa4YcDBdwkK73/OdQgnaC6hLtMlaccXOOh0i4BvqYgstkS7ePrxXS77eHrkxE8sQYkzBoTE5HAemjdJIOsY1QJpPwACsjvWoIMz9qkCi5OIckUCk/YFLkklYRBreSTU4LF5QVa8uywGiNvnFJoROWQWgxXISTVnDAjJwcdmcCvChLuDgkouwBFg95wo8imFqnqsbgEb6hFQKLDoIVTWi50qte6voKKTfM97LS5hb7cs8awVzwAOveu/VcNTiBN8tTj+9jkwD25OAW3sb81ylaHn5LNuFDv6NELZxhSCQN+MhBGQq
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
