---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgAiMj/6HnqOtEW492y6mToSIIs8CLSpCClmhIgYeVCVJq8keCmw3A9oyYxc6juaaURIc7987V7T8pYacsQhNpqQ+q2zlpi+d8tlF7QdkleJfE/RQMZcJtoNifUtpf5ka/Nn605v/zDNDNDvuegdFMtMuV4kKncsjRaGbr+gv07WM0hD+hXRfyrQsvHBCKqF8/QoiJ7xs+734JNl0/wMW8KhzXeYoqH4GRMkhzGJWELARErJAWpbx+csszcxIyId1W9lOKmuqQb1N54NXZxM3uP02jnITY2Rxj7pkCK/bJeLr+qSRcC0OcZAZFB4YmCERQRuREw4vK0rJ9fOX0L06o4aEn43x+jP7T3LqlY2TkSfW9Ws3dyRw4fYTao0PxB+//A4L/phTCUM70sc2inXiLbl+OjemHuChTXC6uf/c4ymxrVMMpn2UPQmPGyHE0ONvGIj6ize68ELYFnP+w5gZsVTX+GWzTPo628q4XGWJR4Og7VTo8D2nS75No9ZTPnmnBoiCd301QTjKyN2Sxbnbm8sKtmAsBVIJz4qf5HCqFFuETwZLJMTRtWfAuQhLmHy3JU4R6xO7eZhPA2zBBBLvrBcaff3r4+JbsYg+UZmMY9W9Npk9bE0fyryZldzQyVHNFHwhBZ3EuuHM93+DqOjyx+Ay5d8QUvHDrDQ2fgy+Gfl83swN1QG5VmtbQPUMVJQeEpFT5awLRI6ib1YrWa655Q+OYgAIAk/gmxiJXZumucDZtoqDXx25rgs
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
