---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgCSb8hKfQQIl+zf6aQrSmRu2gxMqpOxChMXmv2rVIegilDlQz7VBxJsLNWZSIQq/5TMxm4R4EzLX5QFGZGi7tZ77FDmH6RuLLyv1pF/DLLsgNXPI+cn6BG5LDzyetmBeF8ubP7VEcke2Pk5vjWb9uLdyrBlZWuM9bpgBD8pnBmkdsfBt+/d+osXE4BkUPI2ytL7lZKvqHpzPsFmwSfmV95IBU0r2bzcjOYGtUX2cVRCKmpQZb316FAtV+bZXSZ1SqeTBlYYS0/wENukNskWnRYcnqfyVlHPBxpyAiy90GWOZ6Ip+Uv49FJ46hhqHBD+h/hwrrNhPUGGN//sOSU0cdER3K4rccIoaUGn2RVkpnehaB5UWQSMVDrOIMyw8rvhUxoVKNcfgd//ua0GtYpHyVQXctCpRIRJJDByaXnA7pUUENoRmrGX9tXY+h7ZyVKyR+LUVI5Bslo0K2ZiHkRfcSobTzOh5c2cw8JeaFuogZgDmSrcyQeM3cM3UlmOJCT5n1EWHPm77xQP834sFPAQbbTT3t+iuE/btwAY06DpiPNFurz7O2ur5IoYRqcMWaEx0Rtp7+twRWcKhy6LMX1TFXc9RRKFUSZ77JZeOtd+r0XpgcNfKiGwi081iG9ktRsbbhD/VGl+PdYQ/LwstlVvv/Ih9Yy1RG8I6NrWztwkEMBRbwap/KQ8QXezJ0SPQwUv9sL27GvOLvho5LwNrDtAEs7He3AqU91pw+J8Wqd1EMAEw9nubi1OvBJ+
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
