---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgAmBADiGNINNWVtNsgo+641+m3wmVirwfYmBtf+RxlFXEt/A/dAYIejXk90zWOFBzo/0cdRyaC4tXJXs5lxjkgCLT/Esqsp38bdkK4yjkr6AkFTno0JaGo6QB+qFd3E63zVmLkGLcpW9w6fiOi68DWK92dDZ/e6SMtKcPa/Pj0G5m9t0hC2ACCuXcUcFEoJI/3Y/EElMUuKKcYLZwnip0RlLFZaqNBHkt86Ly9mXNppu8vR/C/ZUaO5dhHwIAIHte8B3OkrLjuHg/gQgQpsQcnrwmgxtx3CW0HkNsq61TQrGYtWcsm4mjqEZbz98cjS8sZF/etGN2W9GbZV14jqbctzyNycB4k0s6vVUttJHmnZO4SJxnhEshY7No9bt9D0mPPQNAx7NPUQ6Nq82bIcFGlNZd/fsl/iGXZ3OazPX2U5G5nFFDgQCga5dRuD2KADUyw1hrdU2HovevPvbf0s2qQAEeL2Ac0Tmz18wLbr6Ldxs/i2NsVR6Gw5cyWBFkwIXsVf70fzS9bm+bgReWSupmpzIf/PP4xvdqH7Snnbn7TuicTl5JdswnqaBuvynk8I+kMWPcJiOI2/pVtmubTEI+RE2foZ3PmTF16ZA5H/KKBMmDsoCBWLOLuZjv75lBhpxZxGISNlRWspDaN/VFDjkTiFF8uEpmHK5N3VHVFu3/NIa75KY/NvnrB19ZRwJ/JMqVDin0e4G7pSzk9LI4qC4ssJ7L0Qf1yx67YjDM6IjcuLRzutfQ+ZiPJx
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
