---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgAcJIZSWETmDJ/ObTSLO1XIHg62WXnP1iT+EuwcvNmjVWGDEtqTbKvMEQ99Gfp8LXcnh1qxZuWvuuo9QzKcO6P2W4lk8HWlS2WusZKc9CuJgjpv3+xqQrhez9o62wlQvgmUGV4OBS/PTTtpBCWOR/6sWI5aW51vQfdTVzKhvSzHxIZCwdOfr7sXR+teFeUHwJ0nDIIMn2oELDCA/jU7LvXF1prs0SOwHjYNofZF/KSiGRHgcitGzl7VStiy0Ra5TapKBTgC93dKQJMQX+yLDD1MuAnKziLSm3SrzwLtl1kbpKON2QwVdlf4pJc75t+HAO77JNsInH1SEsaNzWUVJbm5eWarF/yJM/gn2IPrNI0lRJwBLdzi6h+OQCfoJOpc3NqyXuHU1m/ejH0HvFMNiD2qm9XF4bHO6/O7WW4Y9Yr5q7ObRoA6JHPDnRViOemKi1vIhEAEMwUGaXN0jQ+zo9WVa7TgLQ4lv4V16pMUaDMChE+x9nuiVUuVVzB/Jgv0lynxDwGzXrZz1F+pmL8Z+EjD4TYofuZ3xxZmFsnNKUDSTpKy2cWyD/mskZ2/915hZHMZdb0XXTOlOdHfyLDMbaEiX4l0dNYR96YmsCEXCnFhbajG3HQ7XitSUc6IKsLeTyKadwps6FdO5jWJSfP+zGu9B5tEkB+nQ4DD+57VALyVgjt9SUu8cEtCQNvvSyD804V9iyllfHFWTj/j307eWgDkZasvEySVsMY57AFjzdx93K9NVYi/0pcq
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
