---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgCf/IZLJ4q+tKLIPz7ACdFyxT6tNICMYc0fnXUfxmsLUf7kGzthePwVOLXXlD0SjT4uwYNJ2J7h5cqI05YbQ5aK0Yepeqw2KPGQrAFEzKi5VaMAPr8yknIO3eTukDmKhmE4UuaxNDPAW4z4DeoRQYRhkKBdu5TDgLlVIEFzCCc6Mfv6/WZ34s9uXQcSCI50udcPSn60QsnmA+PzdBFhOzm4q6Og/ACiN1zEds88CxfFvlQAn+23fgtCTxupms5NMmK5La6BZ+DbwZ/zQ+HKb1uFlwdYclpLvgEiwchNRkDt68BRq7EywV4ZdBo3toNC4ewddEi6fjatQoaMBw3xapeficVNSx+E7FU9Jh4yIbe0MhQcoq3MczMYAYNOikSt6S2vAg5MO/5hqiB5zPFnlBwWlMEIaSlSrgyqvR03VBgr17gi1aE+iU+l2gNr85dz6Ii9RpCepRcJLtF/++GvNXkDcmF225j4TTR+pDbufZN4XhTLXs0lPmBUFkeA21IKVoA6Xdz9M8/RrLi8uFxM13vlU2AsbjZGbtaRUA89JZbYOyQUOPWHZwBYr6p1aXolGFBftw/6Iv8xnGFASwasMr3InXYRTfV1jNHQC8Rs3Sx72EGmIJ2rRXdE5x6wJTvuFlhRF3nkZUJw2PSW6rjQvaG4CrQNO5KrFCqElOtD5cfUA46Z2q3aYxL455H9baBWZqZXOKv5DYCgZCaYclEiviBATKw86mPH56HnQIgT2iEocirTfba98uL5
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
