---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgBoBvpO1/EWRvBHoda1rlQBxMuSGxwkggEgC5ouQWJMiznc7pOZPiapGjhiXLUqu8Pg4ek4hjRm+tyvwruulTochPTZ702EH7QMxyFp4eGZUIWUt2n1BqqdTlTxv25cy8eI99D3vcr9+5XYmoYKgn0Yiwe6tI0ckCBuDrsEh6712xR6fSBIK9SiJSmbCXpAQG7vrhucd5KsVbUbdNJi1Q/wSq5XIknFV2yTDTt01X1ErywG9cQAJdnoLutzwGHETdIuBrAQRxB76E3N7ivXvPgbi7gEXK5RzKqBrx2RBUT9cSay1K9JL7nOywDmyVCnL14pGZpln5o7akqqHMK6XUQ+bP8y9/JMEwrD2UxwmnIn8YdJOqSbC7OtVLVRJ9pN1grrOGrHyReQDjJFIQ1aao1B0ZW8YZBLqhp/a2tE6++wtUFC6or30ESOp9Bl9YDseT6XhIY9lcJlns7ePW5kyQ3PBFOxtSk6V2wGOP1cXOnhuvjaeoDmu2jPQx/rCOcSXMmsbytDp6oSCd9YLL3RXVg3PPboaMTxc4HfsUGPHSuEht+pqDBYgPlreyFOTiIvo/NlKSwbiYczRN7KPmFZFh0atu+SDyKd1B1VKZw0ahn4A4fKI2JOgHCqLwM8QujOOmmo8ot9I7ZwNl+596AFMKosAD/pL+NO5TKObf7E0QS1snYro5G8AGeiZYmRyrDvNxklj/QVPK4iMyk4McwVf+/swmP9ixGiOGeXWO5u98G6Z/ojjo3UJoS1
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
