---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgAdDnAQTUW+ale9gRPvpMoFlI49vlexM9dJbJYCepZ8/NrFgs7upzsvcn93F+iV/FyH/DyiT8agDe9doWG2CZ8q9xHjEAZHL6jIbqzuHDr+GmkfwzUmFvgS5zwKo3T9Nm4RWKY3FZwtYHq7xi7KjVa1lOhsq5nCxg+es5ADSZfkiGGmCQEXxDVwrtS66IrVxB/+nlzrE8+tgj1JHaCCItZ1Bm7K7MhPN/lIcTchVddugCzS6VEc/9D6LV1CsXahfSCdBfAvCKhY1d99sCPdUcPgixcQNPS7ZMg+lAeAAd6cH+tdm4SKWFifXzxPMkoc+srVO/kzKzi4wSKlKiN3H0VP6n2BEYW0p/nHTAYanA+ba5gLchrEn2w2fhMAZOBQkRp/Rg6unTyvg25CUr4pBqziDdWbjVoju6KyI6kQJsAeY45HNb4eRVi2JeIbrA7XRaIsVSBUjyIERt/GQRHVjSWC2LpiQFwBaAcnWsolhmmZfyTsStNswuFoNPUAmJapfVXHio6icDU3EkoGAjSoYQ9G4LL2wClZlV0fEN/aGqAGdpW68qk9ENYK49CvDHM3gOlfcl0emUTepjrB3l5OBiFSh4sFnhQEF6msFLYAGf2ETlnRBjY83s1TKBfMrYmKCfmqvQlHMpGArY3xu36r3izStzZqpVaiyegZL16LrSOpcu9GlMbdSK2lFo2JFqX5GPAQlcFYO48az/qgx+ANK7va0YKCszBbB5VAIVrdoL4qt1cJ9y2fPxGl
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
