---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgAFqjGWNugMAwhrULR/1vsWy/eZ90ioggMBMsedyh8CnEx1SHpKni2rMsanknEFCmBjzYyjEql8Iju0gwPenYLlzh1/nnl4L7rLOqxqhqN+/i3oIv71qEDaKy0hp7w9P55YobybMkZM7JZpHIMiCRiK6mg0nbLQr8/96Xhj1si2k4pEis/veYnwRe7yFIz/ZmwjBcN93wipJeeN9QsEISn4cddQwCDvmAOx3KZNGqlso8Xd+xmvDhs3vlOuvSOFEMVgHukFQ7ud3rJ0j6bmX68pGSj8p/m6gMDRznZAhgcTxp4MeuNJ00u9PlX20S5lKQUnT/LQokJ+yhhX63Pdzj364XO1IIMSyCWTiM2zaB3hWKN3VgJhTjYHIMF5+VAFnHHj8amZq1TQt9RQxhNHvshT9XfXjNkTDCQtTDwvyQfI3xs5E7Muuh6TatI+7SfA3N5bmAG/p2j/gAnapiZ9E81f56uT4k/0CskWnURVbWBzo2Bk6AZuw3dmIOlzmCMBcOUbr8MCVkgBQfYtVi0uqc78D1CBZ3sycF/9YmubPn7V0lcdIZL996mLH2jsgo4r8PIPjlvpzQvX9LJ/IiRPI0cBOdEAhdF0RE0Q/DIfBp2VFFA9pQee60FjGCnXrRYl9jKhJYQ8ks6sm8wR2cXp7xwYjI2scV+LLv3GPRsipKPKUlxkCnlZGM0p8np87wjibFtz3V6HSYw5xY03M/6xpSlGONWugohzpuMdJimpmPUZPKMlAh8Up1T2mQ==
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
