---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgBWJ47zGc07WzfKRxMFUsTg3HG05EeMnXAQUf8uHKhwxqEBlEBW2mPjCAwAz25ijw2alkN9hanZg+EEdWvG+EBTJ8nd3DbrHhwxxttebFyMpIP2gUBOp4UPyY6QP3f06r34bB9u/f6zfHE1WDXUFFmzEPJgtAY13eObP6Tomel6Q46Mq6fovnfv42sYkVgInTpa4xwvqICaxKlD2wELnDoYqbCTPq/pQvHXwrkB4rWb3a68mnghiExhRsd9mev3RDZJzjuO6fy7pqFjgwDDms7cs05aueZ/agFMuk4l3q/N/Hu6fL7Np42cGNDo84MTWBevLncSWi5TrVq4n4iEgihgUYSiBfkeTPSpqn5EYpYEcxvis4NY8wHeNwqEv6rMfXiwX9N0HjQ2k3i7Pue/pE8rKa0obg78ZaGVb7bC9vFpgvwNAoXRz7LyLCb1CZOGu0Jfrg4OllFBa5cGQbtrJH3iocXwZcoHWqeQUZ9HqCR6uPCFl/tQ5oLmVsA2LoO0GKm72DltoEyHnmU1mA6UPuGOL0TVGChwEOIgEuxlpka0aQimm/l104EvRHCWA8ixwcmcXXoBGZqrtvBrx4Iqvlg0Xf82J7MVeyfTrOLPIvyJbXDiieuOcwwd0Wx1ZyUTF4YmP/9haNQFlrrqm12eaC2sHu2MHTIiIJ3w9FPX1aBtKNm5l+YNCLD+M7/HZJRVOcL1TqTQeYRHTPFH/bNBmup3ODnxJhuG1hdS0UcX07KiGSqSNKzT4oPa
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
