---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgBzcypryYh/RCHde2mJeFjrW6FXjuoWDGKH94fqJuKrORMjhoriygVzcbgKLhuVNOff0rAQyjJWGc9W/2zGY2DkL0jELYt67b/pwcd/VBIel+0NdzqawH8qIsCWnQwktUCzHu3wBbs9jMCAYCs5l+hTnWw7wUQ9UP8qhPQzWHNI6wJJiJvcpRhHsSPQItH/nebyNTu6+P6CC4+udYB8tJV7XDwvJvZcoKA5dDZUCtAr9/RvMstaziMQiZ2cAoMq5RVne3LhpaeC/F0v/gB7XrjVfVMWN7Fj/sJOf0ykQY029TLs/muPIQqgog60TanPhZF4IYe9xABI1grKi3ZDPUl+rKYoxJTV61S8Zv7TbWDhdrfSHiPnyf0BKNca5JZ2aFkcSE1+cVLf8OD4Kf/qE2tEV6FOWtQ00J3dKGqd3HvgwRcevVYsc8QnWke4Cx1ULLTbU/iL6r20zXDa2d9gKSYeawqZpFF44p66SJb7AJEzQ9K07VbnKj7ehHkd+9zVS+CeZaG9kYpjhIKn/x7xHm5FC4/B3ksgTPDkWyuYzk5t/B/EWuFxhpdgeEpLFR4AjeqhJANXLArptJfb4I6LXm2YhNseBnI9hzXJBBoMBWqJ1Nkeg0/06alRy5bi3keB0YY209dds3JDfepdizhaAu2FVq/M0hS10xhzWc0ckaBYp4CAxxBck7Hu5kboynB50Btkz5iadeLBWfeiv9NtoqimQ+WhRrbSrEdBkMu3BMyy2FVM7MHuh7YN
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
