---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgAl12yEdzpGvbvP070hmjW25FkLr3INMR7OkgbFLeI2Zsu9+UMx83LdmxNyeUxcHLZaSsfUK5+MW/zPQsRx7iXdjdwKxcR9SfuQROaje1jLCKE6JKXu+QsFTaQKNZ2Jw6olpDKJ9wvq2Im0R2e83UN/6e7bpn9wyVXfi9oQGKDWUsx8w7PQp6InjU5+Amsju4Oi+VWrhNendKXt7wFqxR/ct+ZbCYyhRREXLtpSJrULKHMEEIVeHz+G398yNbjAhhFgaYsFNSitmWxy2oM+sanonynbSe7Bt6iaF/pdQsuTJAkt9J1WXcpj4TyGlCJlmgxU893iPOGO9R0rHLmgd1JuI48QBaql8onZ3dGPsm1/B44mOn8Sgqy7EVrYZKhHyx5HkwLvprLrWbo7WWUF1p7kBH8TUkFxz5sFE5jEOTwilUEDMsQW7Dyy5aWZBNIbuN9AS62jqxgy1TIMHcEAat4WhvRQbWrcgW5I1ayiR96zbqR/N+7V5MPytoyuSWUUpiRiCH2m7pjtY0NLrsPRD0AcREHLSNp4RsFYZayp9FaGEuzNTOzCLKN7wUKAW4zDSQUR96jSBPIiP/3ZoTnvlNv1674g/IQri9L/HXgTbpd5b+HJL3TR9hwEgteFYiI9xmLmSTJu1+EiaoQppNB5gw9S1VPotqGJOfJpyeSl2zGE+n8Z5OqmaJbOwQJYFQXM17eyjlgnQsTcpIpkhJ6gCI73oJER+7+Uv1EnuLDGQjQAsA8qUzLpfRFQ
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
