---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgCHOPr/gUSskoCDcDLJTKmwEqKDlcotB8Ts3dyDGsx2QCOUGfzxch6yLL6Fb+23WO8O6Crd98VWQnatUTzbTvznBXeJoosoRhXn4wV1wYWVUbRo6969AMav3ToF7tk3FXSSWYfZsLu6it0jMbWNhJpI+cGIal1K1A0Wq87nR3RKHBRdg7jX6bJn2uQyOvZ7NQv1CJRsVDIWSbaXxctC48iFr+3Z1y2pr3ECYwm4Tvb+x5tr2DlKr+B/STHc6xgZhoQfoDkj2jB/+r5W3YL15w8+LonFCxpgnfWaQAcnkWmI8iiy0fhotBfxIUQfk/vkr7OWToO1yBR+nWgp0IHBwvLrUi/QNDVzRkFdduX+m3QtpTPw09w1nHsWun5xY1Iyd0XY/ADhLH6oR4Af2mLzqeatP7b+la52Z4fXGgy8ys+Gvjux3O9MXI/73QhcoStrwqXGB2UJ/rRb3sJqMxs0QbjDf3XnHnKtLB2X4NrT5A5iO1eMxYVoqxMoYsRtZCoLvsOVTges+63wPS34kkadhj4UaQzO8F43ByP70j4bDVOeYbpiDTtgUt23I5rkSyt3YxhHRAITH3CbiHtuDaXwNeTyKmMYOZjSQvHADMqh1Je6fygs2+MnopiQ2vJo4OPl/ZQPnY4lSHCHCbV+EHRq32S5HwnQ2V5XZ3hm9tO3i6aKTRyGbkw3rwhjWA/6HQqjwhjVAVdpOnzKS6DhIC0AD8sjAiFN9y4Lvpi16RyjCH0xQa5dcjSKjmuf
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
