---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgCxvc7M80cdaCsF72wN7K3PjI+gQKF/2Gxug60fGaNk9wjK111Hm5Liey+rXf/NTqLsIseHCHBbP1zBCswUmqP4a2SPSlkRZZ9jncmY1qq9bUdNrXE3/PlNgHmt9dygbR4FmobsP8TT6TcI+oLqqAn/+N5VR+loMMMLW3OHh2dM/fReDVfb1nFPcfgrOfFFBR1QOAfK8T4Zr9PRaUeEYDvMOF66oJTMrZMDyOxm5Y4aCLIcJoHShYDmUiGgyeW0EjrSOwuAh1KkOsYFF+kUKDYTUv787DKWwYQ7A8vOqXt73tkMpGOkO6aSCrJVVwrwmZUz/QCM3+LspjK3ug+NFh7PxK4E6Y+fsz9Ja1bz5GQ/kw3iGcbd7J9238hb9U7Y6LOO1/JmWz6sL0Q+QadKaj4pfSgQmiKc+Ixek1WKUzzp+u1z71y+wnc4zCia7yATb6iRVgk8HH6c8E8Esr++G4GzYm8+mRDNGs0MZi/hoT1B5/tg3YjXqzs0jeU4nBDZ4ROJQ6EfrL3xnuOyDpiROhOT4HzLGKHMhn4nMo1JDDidhtEJS3UY8am2dL0frtB25eQrTuJkNZ21aKBM0w5y0vIPwN6lW9ygAl+1YVcKIoHmecLsrzKrxs++Leqc6MAvMB7DamZ5cZTLBlXvteVn7DZ34HAkSn6UHNY4LDjN0G7+XZQO2VgPCJJhWvxbLNHdtbFom/bMBNfaCuJtAHRubNpRvvm3pVRb6TLXMZ2LJE+8cn/hhuTwXEeJ
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
