---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgAltWC2YZvZLcTEcTjHxSQdGQXvpc7Pt7Bjq4Rp85+f0HN6VB1Z1ZnCnIy//RY77Fjbpwh5AYnrJLLrII/MvCdov3txq//DSqck2V4VhcYwIZrrjChOoVI3hY4hNhN7LuzCkvZa82GPRte0FiSih33PkFcWFVQCaMYmgY0O1QlxkTCepYWDMJh6ZwEfDmyA14xoKIi0PetrxlWRiu+M2y2m08SEnpGkS4+v/sixFPs352x2vqkm2dlt0Pjx/hH6jKocUJxb2LVaG8YBk6L9XhIQtNpbnjSXNkW3uldMbdwUZC3SN9ebrPhF7bYfOG4To0NTR/c0PLei02r4gzhh4XQzBGrEvstuesHgG6T/hbqGSKMWxjlRHpb5GKoPIGLhSoZVrf2lpplsbzuKwv8QfDaaZRXL0Q5FhgRlCtYN1Jg0ULYARR+9QRYBQewxxh1sAmUm3grpNT7oSmvec7ZWuFBXLm6zw26ZZDT7jb+Ju3lfmJN6/MAVdwgJd7AVnhQ6EtM5MxphuuQn0bkuinMBX+Cjux1N3m08IQ0oZehC0Nx5UacyAIaJ+y+k3tmjAfTp19i67dJaX+vV/XPZVcZdHs2hXOwcY4rYvlEYEMsZiNLwnAwmfMUmKMKPqw7jwUv2hJCK1TQjD+4Z6KWssVwjcvr0WBU1M7t35jxbRFBYeBcOCh1WHWcIWRMDkLGQ+gX1HS4D7zgnn0N0YvXuJTnpQVgdzIqRrxFSA2xD64gBUYF3E7mkqAsLMxTX
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
