---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgC2i8RihNW+6NC7FcVut+6jVn0C51jX8Yt24nzd7jXsLHH21A2TDZwrkLQxfnz4C7WGZ98xQHlODrrdJOxpLEYhKXum4avD8STHcdOk0TYaRa/ZX30exE++vV5YyYGhb7lwCXY/kzk/iN0sg5nNpnlSXnTVlPsdsSqYFraphVfPOYfqBpConJ2Xq35z1ODs8/Apsf02Jh73HNgFcBv+t6NzEm/DBfW8DvWlHELTX26GbTe8Hg11+cvRdF/Uvlz7ELPK11RG+Pa5Zc41IOmbR7pmI0mzOsJvlDYxDRSf77onFhBSZE/CD3Ci2ZwxfE+E2RZh7MPWIZNVUcGsEi7URrbIxDzeEMTJyoqfekxLGfYPR2TokiQ+PkvokU1UGssxRdAllQJn3zleoJ7fPxjTGnBS1YxK+U5ynjHEwVBLzLxzXniEH1Co707CjfgYzNPEwlP/TK0IzqL1+yG2MjS/4XHokPcbF/15aUxa6Gb/0yOuhOsyXaY0l9ZERZGJCorsjngwM9mpJsoBGCXSGJfkeQsUjHtCUAsvGTEDx/gr1UIuWVv5TBnEZKczRI7hkPiEjgqTnI7tQ3JZs/icPBHi2hdJrhWkVOjUPw2F6YHnc3tcxBQ/XWW4gGiJjTxTlh+oswzh3KStJRm6bBZZ48vGuS1GrjePRgRH8jcnGyl3zXX2BINnfZeqvEv8EYSF/2n8kU5EMFxGCJ1c36mSjVw5k6BDfr5m9rkbWaTYYmXovXGx9DgCg2PLBL0h
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
