---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgBllzT97ffQipa3hefESfwlABDMV4DtEIUksXrqlNjF1eyT0nJ5NHpbKXl/iQ2IIsLcf8VnEc4hwvcDZhzZtGBQ+W2mqr9ypsT4Llg+0QPjgfhYcGa33GrUT0W4y54HXOMPH6L9ddKBEPoLdQTyhK14Yp1UE33yFlz670XDBv4wFPAF2TmQnI0VjYRmgNV5/t3ria+rQyPLE4YN5bb6OmYo4yPYOcwk1v45hWoUCyT8EmsGPk8oV0FQywb+B6U+6DQ9VCHhQBelxqtMys+CqcEbm3l495eBBgR4CngRxHwry0Lir1idb7AVHUA3ZoKYifQD6xy06taLJzuDlds+hSmyl7vFxvYcBn9E7D/BCvnsoX6cM3qm8qp8t+JkA5+t0z7cVxgWVc6GmxVkllusXjP3y1MH381U4nS18BU8MHQiMBYdhu8hFIf9jv+Om10v/1qCyhwnVZx9nRTM3sSRhg45ePxnlnxxUtLbJnMjM6mU9pjJG6POjcmLGL3yvQxCWA2uIer/laGcOa8A7IZrqZI9JduaPkMMEBX4grp6Us6ZBMJY9rXZ25PRs4HoagTYrhAhHi1qRv2gRuKL+sZFg8CvY5rqKXtc8L/ttj5ktAczExs9lwaAE3SsZvgHl5sZ9wPmjKes8M7yTiyQ8CsCl1JoMfqNI2FXzHDXW3SPv4Yi+Ec63jc6tCBDoK3Uziv1SMj4zUqKC2vzxIeHc8D9nZAKOqXd3onn69kfCRUEdnhNPxK3mlih+15N
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
