---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgBAElZ1KXUt20jmN+J0MfWNEL+KxYj5u8i156D/69F8HDQf7Eu1N5ltSEZVrk5LGsn4aopmPa/4gLNaAZbKkQIkqg7j28gVVSWko1TOtSmM6+++uwLlnFT4Qh3CFtt/2Fjgs4uNEwmpyuMSzR+nOJgF+T7pL+Xrb0EKgDJaHMy98AaC/pDpizbFA2ymBz8NtLYXaI8KVMvjml9oI0KCYisEJ+7MCvul27CZyNQqlEqmVHIVz+ZPhSvUQnOe1EB1vU1+5hpT/Kh7oyv5FuCSGvz9kV9bD71ilJL8YbAAZisVe523RKATl6OMG2cxz04U1L2r/Mrtm6b8I9RVQ7WLdGtBBPZwaGeQQlRsW3FATs6UFXIACosub/kQp5KHT2/W+YJQMKtbcWnD+7js7sieLrLJvUtog5T7N0jwsuiLqnJ1D74F9K9qr5zyJBAoJ8GNzcJjEslD43uL8XtTlqJKp4PHVWwwkdg6ftVi4hKaudK0ALTJw4iLBj6u+vpNLX1RIbuMN/534m/gUiAi+/9l0pI5NeXkt30sKeZUIqML4Fkvio+lHoIbibwcgAHFyQFahDpTxHbqolD8XqnLilxYMGyRaa4dXO9jsbk2Uq1nET9h/1kGAeCg7yNc1Goj9g/wZmoOy59kPoLyhOlA6jwjyJ/YgIJ/QPDD0gmXhHeJJGDYEYZtepQWww2pW5T521b1RWgNi4LQK46f5+/jE1f7LmUXkgdL9Lf7ss7vZqcxah3AAQj/1xwj/8LZ
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
