---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgALvHzd+QWblN/jQqoloPBMdn0RqEoFyXrYivpXa/rUpXrz+abNY139XwQ3mihMxK3+uandleDT8Bq2osHAhe/B1oixlK6UGi+1v1mkJfd72pmZQ6CHotEssnvXAiP3Qr4bilrBXldYCsvd+CoP4w5fNtC4qfE7ycNnM+FIXrAt+N5kW36sVb/cbAYlqT0kU8JPrJ5XqfuxozWJ72r6R6YIy89qSjc3mgrRRFuNqtW9wIemNKqv8XSZIUFFmKpSdyKXygKfDZck9eiH/5+4Eci03xJXhg1u6W3OdyzfEI6tsJ0ny/fgH/Nd282RfTdet2WX18oruHZYdoUb4BwV3dapkgSgSpF7RKs3VM8PyWpee7ma4lESVZPTY9R8f6x5Q+jZuI/l8Sy88atCT0lvJg+SnS9zOPBhUGwIexxKdwzH3+553/b9UPzmu2m5x6jL18Y71fMNqn30D45ZaBAK0URKa7flF4fDrUSx4DhrWwiAuzVEbJ8j1ByIK124CiqjXlP6jj618QXB/3g506CX/ACeCncKuIFSRCNcTCPS571P3jnMBCO5uH1TXYg0lGDSIEHLq/oYCd07PkMX7UvhiT4H+pO3jZd35FL/cO/e0KTl335+C8Uhh7yf0kyYFCDTIvI/rTl1pzDVDzDO7qmQA/Df72Bpvgf20zu8OUVdnAiES3PvefPDV2B0j4gxeQEHR6i5XSSKjv95h3ioQKwrda+sFv/WiZ+gE1zV6hXmRK84NPS0WoLnvE8+
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
