---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgB+LK5W4ZiX4IjYUlCdWyVFOKydX2GbCCw4Qt8pmGmECj+V96ITSykqpNTWkF1JVLfXJLV8J654KZ9NF7pIORO8O5/dZD7sIWeca0K2YootxIN38o0hBd06RKzdIHO5e3zLhXNGR6zmw/v0gqTy2J3av0WU7NzlNgSqvP7KiNSUNrCxAH0jEbBSlM+HHzBiWF8an6RKGdSS1Uv0jb6PbJoxriDOf3CfxrhR1HU4j876boC+zVaM2wzxkilTfsAPZ+nsxhc4xibjAjY1Funkdp22DJxKjeSOWHX2YOkcpE8eLgrc8a7pBLP7ow68uPyGvhap93hshN4NSiDrZH6EmZn5p/vZSexUHXquPbn+LSEXlKhujDvjKb/lIR3H7hrMKmDx0Q4N9nromd84/tUyYnHKP9VBMeXFgGJ23wP2SWbaR4qhQcqrA5RHJBb0aSHRJi5BD9hQd1L+K1+jDavjjzyWamSXmaQ5LocfOQTBeI1QWBkuEtDEY4HtByLMHO2v/Ac98rpZP5Au+2pVIo3UVE1PL78qcgtHGH8DVaSyoTjj1T4KS28PLSw2dVxxvHKX/Ey/CA2eDne5D+8R2ItdnAcHDkRvCGR2ToazC48+18pcD/YVCZXHEThG+3UwTHZ4y6Qf2P/w8cSifl8OhITIk3vIQk1EJ5wpicHj9s8/kDHfRcPy2n+hrfIChumYLhLk2W1QYsEpjUDbyO1/dPqDiyo/wcIMhFg/Vu42VX320h0RjtNM87uuAiK3
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
