---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgBn+ZfPUsX8wJUbHLtQUisVhGoj/M3ePE6tFYhpeNNWW62fW2TAGnQ9LNcGdxWU6iU1zM3mL4lCvjr1XcIOE2y4uLBKYNZmgM4WAppsWkrfY6zGKmKJNxngegbBwoPROe6a8EN9QDyr6/liAEEs++kD9TX4hay1yaahJESu7i9kufenKUw47l4QFwJjxW77ZQFRArRa+XXazZtr+ItqEzUVf1G5H+7FCl1ZIeZ3hLkvTIMqaIYLL5NCPajL3iQOfg92HLkLtsVhQlE4t3s8rYMkKrsaMUF6WUBH3BLNMq4WDWnt/Wy+KA0kM+bat5XzbQkdXTgtxbwRDB3nCZBfULx+C42cblb9Vv0TK8CPkUmzmPNIMD0GQF8R129YSiShGNk1kmhuGEs5DwaG3DMaOWvpqejJO5o8XNiWZ6FDw1KOB+nZVnkThwGiogV5CFwBUxNVliuOT1dK1AGQPJ+344e+gXycNhIGOAUdmpJHikyVCL2kWNppC63l7TTDzn/S9Qef30cx+iznpyjxUNIvBgvKoUUrfmHv1uy8DVVEvNQ23ggTIcftx3IVruu2+sEj15p7lqSdfK6oWSNhjspaYwedu1Xc+QvBPlj79FDVyvMUmP2DGHGk6tvDUrbEFVmjn7OftoKQ2RnnhSzsPSDDRwCuYTwqweC4KAUphcJQjuwOabT6oImXVQVGwg4XqD2ufjmhzIYczYUDmB+tg6ZaJjfcbcyLxbQsNLA2e+RpL+n46NZ80pJ8Hxjo
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
