---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgAiCNvLx/gsfJBCduHhMMXZmYydOqihnpPzmhd4Y48LZ2E4uT47fLdD5Mm+Iq55rf2Njw7kp0iv2T3w17RTWWEv+Z/Oaq1f+bzLfiJo2wjY0DZrrFy8Ot4beEx4mSWR4V9dtxi6rK9oVjvqcbTXYrS8POZYNfcLQUu1bebmKBpJ7jBvHM3tx5OSZqacexAuhwc9bY4uwodkXJDVgNB+BdK0C7ta8BWfZboGB8HSombSvbn76IKzYmFvwk1BeYiaBlMOhfwK1hB13WmJ0GFoGbYOXP6rfixJcUEbDM3T37gvJIBP/AHCQvN3nFFgmgln+tqxM4p0VrjyCLAh3X1je/sgbxuVIUq/vcB/eZP2zW7eY/axtm5QEU0z3e4o/O9fggxL6mmWEFoUq93feVCAt+fvhdBoiWf81mI8ArApZfIBlF2DicCR6SIaeySsAvxZdO/KTPbmVRqt74VtoBrmBTih61kFmtM/LTQskEWlgrHpGOs4Qr6j8eO30+aHbunYp1qP/HFs/6rKftYSW2qzex3QfOzDT+FKYr5XOHR1YGfEgZuO/ETqPqVUp0AVA+9vw/UIt/C3cLuNTX7xEhGSWAKv6BAfy5XOQhotAarfCaasztWt4Gc70m2HPttatNnFuuMRJ1VyhLVBd11/mHPRNsv3jwdpzKMk00HJWeMqvLq7EfakrBNHaB5sWxi4yk7Awc1rwV+epOoOGwhRz0OmlMy0ligGsw52BjpGqsCSbAc6ZoGzNcJbAyaK
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
