---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgA75iVIjNGVsMNcle8G+Ba+/LJnrIxHCmAq4Xvp1HtAXfOLNCeQrY0gKUE+CJ2IUyarX8zwvLFSMcLdDJvQIp3rZZGzaRtjVDoWOyRro+vez43cXdiO/vfNH//RakZm3WNxELBT2OfCK1NeOCkcQL5/1bYsn7qhiYdZPwDEm9/OTi6pUZN2OdsEHw7duKPY/Ha5yeodu6eKnQAd14+kVfuAXAnOQkus9vy0//slOZH3Y1qpHbjkO0JyCJ+LAbTyf70cZybcT0TTGX/oPUsq2wmYz+uvIpTnkWFvQvTTxRfkJghhPzWu52XthZwkocGoQan1IDWjvDLhc2vsJCmUUYrhmE2/rLJvEgzOtVKtpqfL0kKLDfB7j+kBVFcZtOxMn04gXLYE04/fPlifl0m9tM4uQEXMVqI66hCw4emHBoiMvjHWj/VNdViK1VjtllkwzWj7o7eXwxdLI6yWhXfJVLgzka7jUeboXygSogGs7p/ywPnXGWLF2aCRvtWxZtSrZN76Lz/K1o5xGBmC2s3Q8CWN0r0uZFzUkLjw/A9N02CnPfnSlaNbDP30DIAey0VtcvsRh1WW2IDOzl0ji7P+A5dRD5oBBs37mht4Xu2pSR1nt3pId/s4SlDM7eRWtcwuZJ+nYIkAIlU3a201hhvrEyFkfE5uIddyq33A4wV4RpgZz885YX8hMqB908SmLUzj6iinsCLZbVz2JxZH4oBfpLov20yOGMtjtK2fYgcXhV+KW8XkXK2RHks1
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
