---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgAt9EmVkN/IERpC9n/BJVttCDCblNmPLzSzem74TK0Nsxj0VerJZSeZ8yt/T5xEKK2j5XYOA/sDwGNOlBO83hfrk2AuznQcIlt7JxS0OMhRCbTBDJUBGR/xqyD74LjKBln3BpH1QBzvfc4CbUKKRKN/Od20q6yaay6ofkBt7+YQyebaK7QavfAxZEfayTgZZsa9juEpbLA4HgI+h8oGk56hshp3RsrwroQmDh4tkfqXYkjvFLxdTxnjWDEqdtj4QDiK4qVd3Ug/HyMFOSaF44zTUHlOin4cT3viUJqcpwCIxxzSuX1jrgk6+N8j6Tu9wAkIICe54iMpCkW4wETV/FLTCBCnaVRNm+P3pZA4os7p0ggy+5EvhaiRW0xhGdE/+HFrO/osx/o4dLoptfAK9KyPjFOY9BSX+7KT9JLxs97+5CYnuFu19aUHlE8Tusu5+rKFrxQELiiDvEzyMDbPNCAeirRSzp+8v2abbAxfC/x7eMa31HEpuSiJT09QthmnnZHtm1/8kMicaRVp525+uCO2X0pRwYtGQUF0pOPtj4Z8LERTGTprVOvxFbj7ASkTI6P3y0BDQnwYj5Kmp49Ii9p4YcPYJySUss4jjQdm+e1+gDPWJ2/r8zRFu6Qw0oRvWryrutIEctr/fnXjgzpiIM+l+f77Iowt+eMWvtX2GFLlISOxWTkDjFjLNlYubPMDM8W/olxpMI5J0VMhokwi9pU6OrwFHrCDOuGbwIO+mJXgdibQKWeRD09W
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
