---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgCJUAI333y3PlkPhHIJra11g/Y+ZCvCHANDAOOEpykWY7ykhna7lvWacO3vRmVpKfHYtOin6zeHLydHhk+HIGh2FHO7gUPFLkHXhmgWUP50GUp7SB8nUH+9RaP//7up4Z/tvTb6fwSkwiWTzZ/e5eyI9WXde7Jr0tkr+ysqtw91/+liH5c3UnPx8gIgk/Ybp/KiXvzjo6r85reQUNQlm1O16fF+SKBYcghqblUeKhzl56/mh24rVqwxMso/5uV/MCYUJeUImIygcwLGNlmZKsn0gJIFc6KJg55ywWf2Hz9lZ4uxX7tTTlx3UD8EGvjltbqlZ9pcxy0RbnYsP5yUhE+tBSLcgocFoqHhK9AnYr/hW6WrMnGEiLiGLymEVUm5ANMjQvG3OhnJsAHxIX3Bii9VDo2ZPO+OwJZK8TL4QAyl9eAEC6JmLyZcZKrG8Vd+WDZbcTKroEcTJsvdFmF7dIVYVxYfWeqtl2dT2kTtJBrarWT30k8DSYRS5b9X2P4LYXWEvzBjvlsfAf79wYcCSCTHu+jAycNeiViQFBci6Ap+AWo5VuXbhFcOmmRcenLZ47JQS8e9pHq0SljMRhWB4f6GYRf5KbzWeevoILA15jLUJ1IsAfh7mrxCXx7TANwpGUAmu5aSz+beC0WoOwrpuxtdeD6at3kdAxEJpzRe88bao9TUTfBqAyBsWa+ZeoTP16bxyyHlcCOIGgC0IeZj5rgmIvUIgcx6EkkrWGfQox6dEiWvfzGSSSqN
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
