---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgAjoHil3otxPk8kDgvDSDadPTfWH6Vkhu0Hwdn07jDbnngFEiJbWybBBb3Vb7t7nQALGFSSs98YDtL7jar3pI09+vKSu4z/53c0hFYDdUYlvtHrJSOmC23bByJT3ohbYrtNItIXRSgzuw4iRthfRkgvZ5rOBxniImmm6BKtEXI+kL1R9NHDd2qFliu9b6nh5+tbWQzEZA9TIphI7bCzONXQwO8Hn/OUOCTYi1hW9se9ntYY9yF4voyGjxZnat7rlpuQpdXL3ULWmcWSqdWFNRRTNBCQ/EB86AKjmeXpvCPnmHXE1lzjHPT2n7BldxCmQrAbEDvC4S8m/dtCFHXBE1E8UPieRuzKiZdu9NyjWArfRY5cAtn0bVHVbmywiRhCERD9VBQTegSuWQk48dEK/9M/y1Gj116XziuqxbAQGccSg3N3BQyWogFk19eNtjZbkf8gUZo69CodBGIJijTeKZxeGTFE9brYfYXOTlMGatoPJ+F6auTNEUB1zYH5fzs2IqnbtczZjtYlTsiLqQ3WaudXrZdGBc3b2nw0iOWbLvZKFtyYvMnXTcX+/5M9qKKFqpF3+mqAr/NLbXXhjuXX4juAh+r7Rfg9DD/kB8zNIEQAZdSNxlx1jKFAvuzursDdgHO0aVjnnyR0wFhFgz7fLKOvS4SnUZQjkopNz1pnV1Z92X2FCESS3H/pX/WgRLMzsv3VusuJuKqEh0TuVOcPK5x5CIYRvDkmEEiitGnfDAFqQN0ynYPyslcC
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
