---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgAjjwY4BO0Im2jXRS0NjBBmIegsG3Wi0AxDXNDxcp5UE8mMDnOCwLloMomvyTyDuLZ80OMRfKntsmquYel2LLR61cZwLkQsFUMnZazLXEw3qyhnqachpo2db7Qo1VjUmaZvKH/J9u58s9G8ckOHLe4DAc6/1PQMvG6fGhIgt5C3UNwtYr4xxcyXi3uWnt8r0IZukSBbkf9NLcWA1e4KXdCzi0pNOs6GV6cHRoyi4Q/8WccXsBdomsUzv+DH6va+/2g1BzzjW1ZyTgM6l4gANzLhBsB0A7IrmCtqCreEIE6O4je77bRPK/r4YQZeWAyrH+V8cvjeC7D4NscMp2PDd6ieeUHdm82IroLr5RK5yrpU/Z5xjX5LX0Bf/wY3GHkC+JC5jmNx4Ps4r3qe2V8/e/qmD9CNPw9Wjkzt356Nwn/URj1SjtOVqMsinXeNoAR7gKhcKuGFWtCU1NiAVIyZ4DsHziK0o3yl1GrU/ZpUl2yEqEewmCRo7x5/uLKA6K1KI3VKqWei6A5oYZsYjZEUWD15i0dvc/BybeaYd7nQjHbkyfmw+uYst3GiURaYwbvP2JZkh2DGO98mnxVojrx1fhdSMfFA6K7S10Wg1v7cBjs/M7QecKy4fZczyDWWUfZwUvU4cEVUisE+xfgwi/5CZ66eUPZdNJSqM1mBlycG7ABXScTDRqzAKyHHTks9jWpsmE4a81Mk7m/0jzlSqpK7MUxiCpKXEspqRwTOmXgTdn8atjobjxoZOHzF
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
