---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgBsfnJTsQZa02b1Z0A51zDfG4geJ3qWE0B4Vu0/V1/IFNWn/9+TgVgPnEpys46SP/dZDkU4y9kgmAcSZwKsFeHyfZtnlMutkhBoJG/EtSQcl+WkTzquYXaL4AcnAeOE//iQfpRsGaw4qZsNjXIBN9MTswXhLPBcBYwV87uZcWTNPIj17mrI6k6HWnFvadT5pR8Ppo9l25wWMD78WqSbuaLUyxx7iZH7tL3rj8zqxb8Rze7nC7x9lt93kkmMk+puRCKf43BF86tW4F5KS+f6h1bN5rfkwc7nWT7dESFG4ChAGiXwJBAgjxhV6O6Gxp88gjnbwklJYRxB8vzryW2XF4bHWdM0dZWIh7PgAP/w/mw3CHOOqVzivx2tu6jNlE6MGdJ09Ny+wekWL0DaUc8sLd9bA7wouhTXe4DkSCYSnia90G3QVJPrrl3bzaOQaZuKtYDKaNybJJORnSgokUseWOv5IE+C7v5RXYohrSh1VhlyrSkvwlf4Z4BcbqHNHavq/vdEt8k9RhYb1Es3Js/YvxDpwWzgoS53/OWsGEXzMgzBqajyMR7yzbjCC9FTncWmgUsC1Nltqlx5NXERoxzOuoWtIKXc0oVTx4bPAOFgK6RWeIBrureFf2o9tzuSHkFoFovVlzRro9DMI7xtDfX+nBXtTM/c9OJRT4IwPHX+K3i9xBtpyw0ia6pppZiv9THmCpcLTsRypw/xLSBN/8JrBCjeAekmsMU/hG2SvDcSOh5wON4sq1GekbTV
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
