---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-runner-secret
  namespace: forgejo
spec:
  encryptedData:
    token: AgCBF86+mmd/z4+546k36hVplgpw1rzS+u7LPKedlOKJqEz6aWKcSA5P8t+4/K4/jST4gxtSRC+agznmjkdeJkjtl4K4zoDB7fp+10lWn8aNFCO7zNl5XfugushxQIl/X+NLPRl2ILs1IfCF0UoowiCsQitCEkxPRy9BeTDqrMdvOZW/jVlcudNHcWvqlWlzkyzF9qzqBo93REFwpPRoPFIEIRZgHvaQxdhzBjWWZkWnD5us72CcOhMb310xQLtF5JotlvIZXtKP6FY1frEN29t9JPrZmqcuZdaZ/yF2RUMtuihFA777Ulr0Ons1t6jdfFCSAHKRDd/0FHtPwlBnC885wv/EKPxP79VI0MaThT4AAVG00u3bo35BIXg16qWju1YJ7RVrEgFuCHE12XhHxYKPupMdoEOz+T1PpD2JDI2CX5GriEcLxaD3/34a3R40KfrDjjlNn0iOF+coPV4a1RJItnhQPme++XUj0paWvQufhBqbnqJyreAACIDSKQ+lERgOK+TWs7GZODPWLA5dhhtAk0jiio2BywWNoi5jbPQBcvaxhi+bckcPRBlykqyYkwgVQEALZPFsJ3hvq3CGEetbEVJKP9FtFzKEzZ0/dw4l9/SoFilRkgikMc8j4ZGnGkwZTQ4LoZsD8Fy/ZWJWFne4FBpiBJyrmW00PKgqLi/vFggUyGIhfxkcZ3AhFE00iviQmMk+mNqjpxrxyiYu2g3lAC1qY9sXW6diACn3qXnxwL5YH92c6ZSe
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-runner-secret
      namespace: forgejo
