---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: surrealdb-credentials
  namespace: event
spec:
  encryptedData:
    password: AgBr694OZgaBg5HZWua3A+MwrPIOz9GOecoMxJic9HCeY92swVjDKE0gARAWR9ZgP9auToAbKfUZfRdrWi4HprrV6A8i8gcH1xdrP4SkRP0DvheG5wfxnDk6fA9ytdWVrtE8lyh1hHnB/86PUJWejFMgBuOlkAqj3xEfLjTnM9p/CT/w1iZclKMq+DZu4jZh0Va55OEzWrWf7nlHRkwB4X31JYE7qfYzYqtl+/4ehPjKRnirs9wQj+UtYabkQ5lRc6vY2OD2TsSkWlxOzwSvynxxt/M1sdfIUch3KQ6FotMHuoN2Yll2w9vvxB/uzONP9SFdOKH+OBKIzp8AwghYiyNBYD9CesdnZabxeR3VyeHz9C4E+Ie1Q54cCmCg7lrE3rxsLUTIDnvu/uPt2a0e7LVtd2j6Kuzw9GLvpCVHLaUFELm6kPrgLNZDNdgqImXZUQm3Kb2TOPNpa7c+K8zFRzsIvEpo8WOk5D22JR7t4vNUmYTUCyMtjrY5gyXN+KPrZRIcCbqsy28K5n6U8/5jOpCpccWpuUQ3Q/ep/YAYhTl5sa3SupogMT+eYRIzO38t+guffdtOTEtgzatyNyoIADWTXzSk4yBlW3eTGYU/2FTGMdhvPNzzSshapJmYgvpxKFAHy75L6Ib63EB+ZFwquw7h+Nd/lGB4bYK2UYef6VftBx1zfSpeK/q2gqOgxkZ5sQK49GgPlDqd3Ci0Cb9UP15XrOH4TdpYUq3VGdzvzMRq1BuunfhA9xYJP0kw5mgjcxZ6W55/XNfh5xsEpyg=
    username: AgCD25JQ4QPPmfbsk4Trq+ul/WvK78Pm6rqRiBpLGMyUSHBXYzt4VJ7u+AGBLrzeadh4UwEuYaNdmNe3yF8AGtYXhWUH8UNdFeuOqHTMrgXMOfXimGxxs9t0k93EXxIUTKqo9Xg0AFsd3wLYGkhDRSRzjtUH+eyfSXx9nni2WwcMUeS8sjed6Ig+VjYCTRV1QAkUMhXyTbH9EGBVkgjW58qWCG+Ua2M4yAxHf90NN4o5B3CxAZJJZdxdl99CaKRSqEunPTmP9q4N9IC0ZMqJ5zQwVmO6J0mveNwxxE/5wnzUG82ffMtDldJTsrTAybunrHJyly9qUphLDjcJnbVbMl61ezp8RuGvaJ2lwKiHOokNhRd9Wv9BxT5L1B76IiC04Xl1mN0pDWCnJiMwWlGCTJ8EBhQCVa6myEU357oSH1GluxtvBQzk/9MI0nP4bAhJFCtGJv/M4/7vRtULLDYEH+xWTg05e1ysVvP4ND53GlOyicoLX0n4gpURdceCNk/VyIuig1YWINAsHWIqbbVRzRUst9dD34Ga7+DMxwZNe85Bi8ywV8MN3vO87YZp6dzhx3aPUB0ZmFaEZDGl6LLy9ZagPxbM1UO9yekqJDEujbxoIOLHL3RmEzB+UEh8wt9qW4dmIOv4iNRiD+woLp31R0z4dJZJiYloMEb7n3X12opS479PJMLzZqTygVXHvRKfUoLiPjS34zG74hiT
  template:
    metadata:
      creationTimestamp: null
      name: surrealdb-credentials
      namespace: event
