on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: dcarbone/install-jq-action@v3

      - name: Write zitadel key
        env:
          ZITADEL_KEY: ${{ secrets.ZITADEL_KEY }}
        run: |
          echo "$ZITADEL_KEY" > ./bootstrap/.zitadel

      - name: Reveal secrets 
        uses: entrostat/git-secret-action@v4
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Apply OCI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ./bootstrap
        run: make apply-oci

      - name: Bastion
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ./bootstrap
        run: |
          make apply-bastion
          make start-bastion-sessions

      - name: Apply Cluster
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ./bootstrap
        run: make apply-cluster 

      - name: stop bastion
        working-directory: ./bootstrap
        run: make stop-bastion-sessions
