on:
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: extractions/setup-just@v2

      - name: Setup Tofu
        uses: opentofu/setup-opentofu@v1

      - name: setup TerraGrunt
        uses: eLco/setup-terragrunt@v1
        with:
          terragrunt_version: 0.77.6

      - uses: webfactory/ssh-agent@v0.9.1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: dcarbone/install-jq-action@v3

      - name: Reveal secrets 
        uses: entrostat/git-secret-action@v4
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Start bastion sessions
        run: just bastion

      - name: Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ./bootstrap
        run: source .env && terragrunt run -a plan --queue-exclude-dir bastion --experiment cli-redesign 
