apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oci-arc
  namespace: sys-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    namespace: arc
    # TODO: solve this with yaml merging
    server: https://kubernetes.default.svc
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: 0.10.1
    helm:
      values: |
        githubConfigSecret: arc-credentials
        githubConfigUrl: "https://github.com/Randoooom/devops"
        controllerServiceAccount:
          namespace: arc
          name: arc-controller-gha-rs-controller
  {{- include "common" . | nindent 2 }}
